Repository atk4/ui, pull requests merged in 2018-10, with the labels that each got.

#564 feature/leftMenu option
  docs/app.rst
  src/App.php
  src/Layout/Admin.php
Labels: Sponsored :moneybag:, in review

#569 Set view as not rendered if there is exception
  src/View.php
Labels: in review

#567 Upgrading to Fomantic-UI
  README.md
  src/App.php
Labels: in review

#551 Feature/lookup field
  CHANGELOG.md
  demos/autocomplete.php
  demos/init.php
  docs/autocomplete.rst
  src/FormField/Generic.php
  src/FormField/Lookup.php
  src/FormLayout/Generic.php
  template/semantic-ui/formfield/lookup.html
  template/semantic-ui/formfield/lookup.pug
  template/semantic-ui/formlayout/generic.html
Labels: in review

#574 Sorting should happen later. Fix #544
  src/Grid.php
Labels: in review

#576 fix/ set input attribute to readonly or disable.
  demos/atk4.sql
  demos/field2.php
  demos/form3.php
  docs/field.rst
  src/Form.php
  src/FormField/AutoComplete.php
  src/FormField/Calendar.php
  src/FormField/CheckBox.php
  src/FormField/DropDown.php
  src/FormField/Generic.php
  src/FormField/Input.php
  src/FormField/Lookup.php
  src/FormField/Radio.php
  src/FormField/TextArea.php
  src/FormField/Upload.php
  template/semantic-ui/formfield/autocomplete.html
  template/semantic-ui/formfield/autocomplete.pug
  template/semantic-ui/formfield/checkbox.html
  template/semantic-ui/formfield/checkbox.pug
  template/semantic-ui/formfield/lookup.html
  template/semantic-ui/formfield/lookup.pug
  template/semantic-ui/formfield/radio.html
  template/semantic-ui/formfield/radio.pug
Labels: in progress

#577 View::on now takes callback and JS actions
  src/View.php
Labels: in review

#584 Only show action <div> if there are actions
  src/Modal.php
  template/semantic-ui/modal.html
  template/semantic-ui/modal.pug
Labels: in review

#582 Feature/jsReload with semantic configurable api options.
  js/README.md
  js/Release.md
  js/package.json
  js/src/plugins/reloadView.js
  src/jsReload.php
Labels: in review

#579 Allow PHP 7.2+ to check method signatures
  src/App.php
Labels: in review

#581 add formConfig to pass parameters to FUI .form()
  src/Form.php
Labels: in review

#586 Feature/demo lineend bug
  demos/field2.php
Labels: in review
