Repository atk4/ui, pull requests merged in 2018-03, with the labels that each got.

#354 Feature/various fixes
  demos/breadcrumb.php
  demos/crud.php
  demos/database.php
  demos/init.php
  demos/table.php
  docs/breadcrumb.rst
  docs/components.rst
  docs/crud.rst
  docs/grid.rst
  docs/table.rst
  src/BreadCrumb.php
  src/CRUD.php
  src/Console.php
  src/Form.php
  src/FormField/Input.php
  src/Grid.php
  src/Table.php
  src/TableColumn/Status.php
  src/View.php
  src/VirtualPage.php
  src/jsExpression.php
  src/jsNotify.php
  template/semantic-ui/breadcrumb.html
  template/semantic-ui/breadcrumb.pug
  template/semantic-ui/layout/admin.html
  template/semantic-ui/layout/admin.pug
  tests/DemoTest.php
Labels: Cleanup, SaaSty.io :building_construction:, in review

#407 feature/Draggable
  demos/jssortable.php
  js/README.md
  js/package.json
  js/src/plugin.js
  js/src/plugins/jsSortable.js
  js/webpack.config.js
  src/Grid.php
  src/TableColumn/DragHandler.php
  src/jsSortable.php
Labels: in progress

#416 Feature/add card
  demos/card.php
  src/Card.php
  src/Table.php
  tests/DemoTest.php
Labels: SaaSty.io :building_construction:
