Repository atk4/ui, pull requests merged in 2019-12, with the labels that each got.

#845 Feature/input action
  demos/jsactions.php
  src/ActionExecutor/jsUserAction.php
  src/FormField/Input.php
Labels: in review

#852 Improvement/include action caption in modal title
  src/ActionExecutor/UserAction.php
Labels: in progress

#855 Add Instantiate App using DIContainerTrait
  docs/quickstart.rst
Labels: Documentation :books:

#853 Feature/enable setting custom exec button for an action
  src/ActionExecutor/UserAction.php
Labels: in progress

#857 Added namespaces to quickstart and file structure example
  docs/filestructure.rst
  docs/index.rst
  docs/quickstart.rst
Labels: Documentation :books:, hangout agenda :speaker:
