Repository atk4/ui, pull requests merged in 2019-07, with the labels that each got.

#759 Fix/Form::success()
  src/Form.php
  src/jsCallback.php
Labels: in review

#750 Small changes to templates (form/centered layout)
  src/Layout/Centered.php
  template/semantic-ui/formlayout/generic.html
  template/semantic-ui/formlayout/generic.pug
  template/semantic-ui/layout/centered.html
  template/semantic-ui/layout/centered.pug
Labels: in review

#747 fix/#746 Duplicate button and icon id
  src/TableColumn/Actions.php
  src/View.php
Labels: in review

#762 fix php notice
  src/FormField/MultiLine.php
Labels: in review

#768 feature/Form Action Executor
  demos/grid_action.php
  src/ActionExecutor/Basic.php
  src/ActionExecutor/Form.php
  src/ActionExecutor/Preview.php
  src/CRUD.php
  src/Grid.php
  src/Table.php
  src/TableColumn/Actions.php
Labels: in progress

#770 Feature/confirm modal
  demos/jsactions.php
  js/Release.md
  js/package.json
  js/src/plugin.js
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/confirm.plugin.js
  src/ActionExecutor/jsEvent.php
  src/Card.php
  src/TableColumn/Delete.php
  src/View.php
Labels: in review

#775 refactor to use getFields()
  demos/database.php
  demos/form3.php
  demos/somedatadef.php
  demos/table2.php
  src/CardTable.php
  src/Component/InlineEdit.php
  src/FormField/Lookup.php
  src/FormField/MultiLine.php
  src/FormLayout/_Abstract.php
  src/Grid.php
  src/Persistence/POST.php
  src/Persistence/UI.php
  src/Table.php
  src/TableColumn/FilterModel/TypeDate.php
  src/TableColumn/FilterModel/TypeDatetime.php
  src/TableColumn/FilterModel/TypeNumber.php
  src/TableColumn/FilterModel/TypeTime.php
  src/TableColumn/Link.php
Labels: MAJOR, URGENT

#788 Simplify setStyle method
  src/View.php
Labels: in review
