Repository atk4/ui, pull requests merged in 2019-04, with the labels that each got.

#680 use read_only instead of disabled property
  src/FormLayout/_Abstract.php
Labels: in review

#682 fix/#679 Disable Input
  src/FormField/DropDown.php
  src/FormField/Input.php
  src/FormField/Upload.php
Labels: in review

#678 Feature/Ui view handle by Vue.js
  demos/vue-component.php
  features/bootstrap/FeatureContext.php
  features/vue.feature
  js/Release.md
  js/package-lock.json
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-semantic-ui.js
  js/src/components/inline-edit.component.js
  js/src/components/item-search.component.js
  js/src/helpers/add-params.helper.js
  js/src/plugin.js
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/atk.plugin.js
  js/src/plugins/column-resizer.plugin.js
  js/src/plugins/conditional-form.pluing.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/file-upload.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/plugins/js-sortable.plugin.js
  js/src/plugins/notify.plugin.js
  js/src/plugins/reload-view.plugin.js
  js/src/plugins/scroll.plugin.js
  js/src/plugins/server-event.plugin.js
  js/src/plugins/spinner.plugin.js
  js/src/services/accordion.service.js
  js/src/services/api.service.js
  js/src/services/form.service.js
  js/src/services/modal.service.js
  js/src/services/popup.service.js
  js/src/services/upload.service.js
  js/src/services/vue.service.js
  js/webpack.config.js
  src/Component/InlineEdit.php
  src/Component/ItemSearch.php
  src/View.php
  src/jsVueService.php
  template/semantic-ui/inline-edit.html
  template/semantic-ui/inline-edit.pug
  template/semantic-ui/item-search.html
  template/semantic-ui/item-search.pug
  tests/DemoTest.php
Labels: in review

#684 Fix/modal duplication
  js/Release.md
  js/package.json
  js/src/services/api.service.js
Labels: in review

#687 Fatal Error attempting to set grid options.
  docs/quickstart.rst
Labels: invalid

#688 feature/Dropdwon callback.
  demos/menu.php
  src/DropDown.php
Labels: in review

#692 Documentation corrections
  README.md
  docs/accordion.rst
  docs/app.rst
  docs/breadcrumb.rst
  docs/button.rst
  docs/callbacks.rst
  docs/conf.py
  docs/console.rst
  docs/data.rst
  docs/field.rst
  docs/fileupload.rst
  docs/form.rst
  docs/grid.rst
  docs/header.rst
  docs/icon.rst
  docs/image.rst
  docs/js.rst
  docs/label.rst
  docs/lister.rst
  docs/menu.rst
  docs/message.rst
  docs/misc.rst
  docs/overview.rst
  docs/paginator.rst
  docs/popup.rst
  docs/progressbar.rst
  docs/quickstart.rst
  docs/table.rst
  docs/tablecolumn.rst
  docs/tabs.rst
  docs/view.rst
  docs/virtualpage.rst
  docs/wizard.rst
Labels: in progress
