Repository atk4/ui, pull requests merged in 2019-06, with the labels that each got.

#725 fix/Generic Input onChange event
  src/FormField/Calendar.php
  src/FormField/Generic.php
  src/FormField/Radio.php
Labels: in review

#702 Only prepend namespace for known classes
  src/App.php
Labels: in review

#701 Feature/integrate actions
  .github_changelog_generator
  CHANGELOG.md
  README.md
  demos/actions.php
  demos/console.php
  demos/database.php
  demos/init.php
  demos/multiline.php
  demos/vue-component.php
  docs/app.rst
  docs/core.rst
  docs/overview.rst
  docs/quickstart.rst
  docs/render.rst
  docs/seed.rst
  js/Release.md
  js/babel.config.js
  js/package-lock.json
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/components/multiline.component.js
  js/src/components/multiline/multiline-body.component.js
  js/src/components/multiline/multiline-cell.component.js
  js/src/components/multiline/multiline-header.component.js
  js/src/components/multiline/multiline-row.component.js
  js/src/helpers/add-params.helper.js
  js/src/helpers/url.helper.js
  js/src/plugin.js
  js/src/plugins/conditional-form.pluing.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/file-upload.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/services/form.service.js
  js/src/services/vue.service.js
  src/ActionExecutor/ArgumentForm.php
  src/ActionExecutor/Basic.php
  src/ActionExecutor/Interface_.php
  src/ActionExecutor/Preview.php
  src/App.php
  src/CRUD.php
  src/Card.php
  src/Component/ItemSearch.php
  src/Console.php
  src/Form.php
  src/FormField/Calendar.php
  src/FormField/CheckBox.php
  src/FormField/Generic.php
  src/FormField/MultiLine.php
  src/FormField/Radio.php
  src/FormField/Upload.php
  src/FormLayout/_Abstract.php
  src/Grid.php
  src/TableColumn/Generic.php
  src/View.php
  src/jsModal.php
  src/jsSSE.php
  src/jsSearch.php
  template/semantic-ui/layout/centered.html
Labels: in progress

#736 should check numeric value not int
  src/Header.php
Labels: in review

#738 fix negative status
  src/Header.php
  src/Table.php
Labels: in review

#751 feature/ js Executor for Action
  demos/actions.php
  demos/jsactions.php
  src/ActionExecutor/Event.php
  src/ActionExecutor/jsEvent.php
  src/Card.php
Labels: in review

#643 Fix #629, also add new Callback for custom HTML
  demos/dropdown-plus.php
  demos/init.php
  docs/field.rst
  src/FormField/DropDown.php
  template/semantic-ui/formfield/dropdown.html
Labels: Documentation :books:, in progress

#756 fix #755
  demos/form.php
  src/FormField/DropDown.php
  src/FormField/TextArea.php
Labels: in review

#757 Add Unit test and Fix some issue on TableColumn\ColorRating
  src/TableColumn/ColorRating.php
  tests/DemoTest.php
  tests/TableColumnColorRatingTest.php
Labels: Documentation :books:
