Repository atk4/ui, pull requests merged in 2019-08, with the labels that each got.

#783 Feature/fix textarea
  demos/form.php
  src/Form.php
  src/FormField/DropDown.php
  src/FormField/TextArea.php
  tests/FormTest.php
Labels: hangout agenda :speaker:, help wanted, in review

#782 Gowrav vishwakarma ui editable bug
  tests/ForFieldUITest.php
Labels: in review

#790 Remove calls to exit functions and cleanups
  .gitignore
  .travis.yml
  composer.json
  demos/exception_test.php
  demos/grid_action.php
  demos/index.php
  demos/init.php
  js/package-lock.json
  phpunit.xml.dist
  src/App.php
  src/Form.php
  src/View.php
  src/jQuery.php
  src/jsSSE.php
  tests/BuiltInWebServerAbstract.php
  tests/DemoCallExitExceptionTest.php
  tests/DemoCallExitTest.php
  tests/DemoTest.php
  tools/test.sh
Labels: hangout agenda :speaker:
