Repository atk4/ui, pull requests merged in 2020-04, with the labels that each got.

#1049 [fix] - Downgrade Fomantic-UI release to 2.7.4
  features/bootstrap/FeatureContext.php
  features/js.feature
  features/modal.feature
  src/App.php
Labels: question

#1051 Use content type from the source + cleanup of URL methods
  demos/wizard.php
  js/Release.md
  js/package.json
  js/src/plugins/create-modal.plugin.js
  js/src/services/accordion.service.js
  js/src/services/api.service.js
  js/src/services/modal.service.js
  src/App.php
  src/Component/InlineEdit.php
  src/FormField/Lookup.php
  src/FormField/MultiLine.php
  src/ItemsPerPageSelector.php
  src/Lister.php
  src/Loader.php
  src/Modal.php
  src/Popup.php
  src/Tab.php
  src/TableColumn/Delete.php
  src/TableColumn/DragHandler.php
  src/View.php
  src/VirtualPage.php
  src/jsCallback.php
  src/jsModal.php
  src/jsSSE.php
  tests/CallbackTest.php
  tests/DemoCallExitTest.php
  tests/FormTest.php
Labels: in review

#1070 [fix] UserAction Modal Id
  demos/crud.php
  src/ActionExecutor/UserAction.php
  tests/DemoCallExitTest.php
Labels: Saasty.io :building_construction:, in review

#1065 Improve HTTP headers output
  demos/wizard.php
  js/Release.md
  js/package.json
  js/src/plugins/server-event.plugin.js
  src/App.php
  src/Console.php
  src/SSE.php
  src/jsCallback.php
  src/jsSSE.php
  tests/CallbackTest.php
  tests/DemoCallExitTest.php
  tests/FormTest.php
Labels: in review

#1064 Remove App::outputDebug() method
  src/App.php
Labels: in review

#1088 [fix] UserConfirmation executor + Behat test
  demos/country_actions.php
  demos/jsactions2.php
  features/bootstrap/FeatureContext.php
  features/filter.feature
  features/form.feature
  features/form2.feature
  features/js.feature
  features/lookup.feature
  features/modal.feature
  features/useraction.feature
  features/vue.feature
  src/ActionExecutor/UserConfirmation.php
Labels: in review

#1090 [Fix] Issue #967
  js/Release.md
  js/babel.config.js
  js/package.json
  js/src/agile-toolkit-ui.js
  js/webpack.config.js
Labels: in review

#1085 [Feature] Right layout panel
  demos/layout-panel.php
  docs/components.rst
  docs/rightpanel.rst
  features/bootstrap/FeatureContext.php
  features/form.feature
  features/rightpanel.feature
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/services/panel.service.js
  public/agileui.less
  src/Layout/Generic.php
  src/Panel/Content.php
  src/Panel/Loadable.php
  src/Panel/LoadableContent.php
  src/Panel/Right.php
  template/semantic-ui/html.html
  template/semantic-ui/html.pug
  template/semantic-ui/panel/content.html
  template/semantic-ui/panel/content.pug
  template/semantic-ui/panel/right.html
  template/semantic-ui/panel/right.pug
Labels: in review

#1097 Fix CI/CD
  Dockerfile
Labels: in review

#1094 Do not require database for array based CRUD demo
  demos/crud3.php
Labels: in review

#1105 Fix phpunit before full upgrade
  phpunit.xml.dist
  tests/ButtonTest.php
  tests/CallbackTest.php
  tests/ForFieldUITest.php
  tests/FormTest.php
  tests/GridTest.php
  tests/ListerTest.php
  tests/PaginatorTest.php
  tests/PostTest.php
  tests/RenderTreeTest.php
  tests/TableColumnColorRatingTest.php
  tests/TableColumnLinkTest.php
  tests/TableTest.php
  tests/TagTest.php
  tests/TemplateTest.php
  tests/ViewTest.php
  tests/jsIntegrationTest.php
  tests/jsTest.php
Labels: in review

#1100 [fix] - Setting value on DropdownCascade
  src/FormField/DropDown.php
  src/FormField/DropDownCascade.php
Labels: in review

#1109 [fix] CRUD::addModalAction to use appSticky argument on Modal callback
  src/Modal.php
  src/TableColumn/ActionButtons.php
Labels: in review

#1112 [feature] - Admin Layout
  demos/breadcrumb.php
  demos/database.php
  demos/dropdown-plus.php
  demos/field2.php
  demos/init.php
  demos/multitable.php
  public/agileui.css
  public/agileui.less
  src/Layout/Admin.php
  template/semantic-ui/layout/admin.html
  template/semantic-ui/layout/admin.pug
Labels: in review

#1111 App::addStyle should not encode value
  src/App.php
Labels: in review

#1121 Feature/implement html decorator
  demos/table.php
  src/TableColumn/Generic.php
  src/TableColumn/HTML.php
Labels: in review

#1120 [feature] Maestro Layout
  demos/init.php
  js/Release.md
  js/package.json
  js/src/plugin.js
  js/src/plugins/sidenav.plugin.js
  public/agileui.css
  public/agileui.less
  public/atkjs-ui.min.js
  src/Layout/Admin.php
  src/Layout/Maestro.php
  src/Layout/Navigable.php
  src/Menu.php
  template/semantic-ui/layout/admin.html
  template/semantic-ui/layout/admin.pug
  template/semantic-ui/layout/maestro-sidenav.html
  template/semantic-ui/layout/maestro-sidenav.pug
Labels: in review

#1130 Update Lookup.php
  src/FormField/Lookup.php
Labels: in review

#1140 Test unit test path
  tests/DemoCallExitTest.php
Labels: in review

#1135 Delete release.sh if not needed
  tools/release.sh
Labels: in review

#1133 [fix] Add stop function to ServerEvent js plugin
  demos/interactive/sse.php
  js/Release.md
  js/package.json
  js/src/plugins/server-event.plugin.js
  public/atkjs-ui.min.js
  src/jsSSE.php
Labels: in review
