Repository atk4/ui, pull requests merged in 2020-01, with the labels that each got.

#879 move jsInput, add jsChecked
  src/FormField/CheckBox.php
  src/FormField/Generic.php
  src/FormField/Input.php
Labels: in review

#880 Fix/UserAction in VirtualPage and Tabs
  demos/card-deck.php
  js/Release.md
  js/package.json
  js/src/services/api.service.js
  src/ActionExecutor/UserAction.php
  src/App.php
  src/View.php
  src/VirtualPage.php
  tests/DemoCallExitTest.php
Labels: in review

#883 Feature/Card Field default
  src/Card.php
Labels: in review

#874 introduce record specific enabling/disabling of actions in Grid/CRUD
  src/CRUD.php
  src/Grid.php
  src/TableColumn/ActionButtons.php
  src/TableColumn/ActionMenu.php
  src/TableColumn/Actions.php
Labels: in progress

#884 set model on initialization
  src/View.php
Labels: invalid

#886 fix #850
  src/ActionExecutor/UserAction.php
Labels: in review

#871 Feature/update readme
  README.md
Labels: in review

#893 Fix/CRUD onForm callback
  demos/crud.php
  src/CRUD.php
Labels: in review

#894 Fix/Enable Callback argument to stick at application
  src/Callback.php
  src/Loader.php
Labels: in review

#898 Add action should respect enabled/disabled switch
  src/CRUD.php
Labels: in review
