Repository atk4/ui, pull requests merged in 2020-03, with the labels that each got.

#972 Implement $sortable property for TableColumn.
  demos/database.php
  docs/grid.rst
  public/agileui.less
  src/Grid.php
  src/TableColumn/Generic.php
  src/TableColumn/Password.php
Labels: in review

#997 fix #995, simplify session object in demo
  composer.json
  demos/Session.php
  demos/modal2.php
Labels: in review

#951 [FEATURE] introduce autocomplete dependency
  demos/autocomplete.php
  docs/autocomplete.rst
  src/FormField/AutoComplete.php
  template/semantic-ui/formfield/autocomplete.html
  template/semantic-ui/formfield/autocomplete.pug
Labels: in review

#968 [REFACTOR] rename addHook to onHook
  demos/actions.php
  demos/crud.php
  demos/database.php
  demos/grid_action.php
  demos/init.php
  demos/jsactions.php
  demos/jssortable.php
  demos/lister-ipp.php
  demos/lister.php
  demos/scroll-container.php
  demos/scroll-lister.php
  demos/table.php
  demos/table2.php
  demos/vue-component.php
  docs/label.rst
  docs/lister.rst
  src/CRUD.php
  src/CallbackLater.php
  src/CardDeck.php
  src/Form.php
  src/FormField/CheckBox.php
  src/FormField/MultiLine.php
  src/FormField/Radio.php
  src/FormLayout/Section/Accordion.php
  src/TableColumn/FilterModel/Generic.php
  src/TableColumn/Generic.php
Labels: BLOCKED

#996 fix issues with Card and CardDeck
  demos/card-action.php
  demos/database.php
  src/Card.php
  src/CardDeck.php
  src/Component/ItemSearch.php
Labels: in review

#1001 better support for arguments with model type
  src/ActionExecutor/ArgumentForm.php
  src/ActionExecutor/UserAction.php
Labels: in review

#1011 fix/jQuery var assignment
  js/Release.md
  js/package.json
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/confirm.plugin.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/file-upload.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/plugins/js-sortable.plugin.js
  js/src/plugins/notify.plugin.js
  js/src/plugins/scroll.plugin.js
  js/src/plugins/server-event.plugin.js
  js/src/plugins/spinner.plugin.js
  js/src/services/data.service.js
Labels: in review

#1017 [Fix] PHP Notice Bad Index on jsCallback
  demos/form.php
  features/form.feature
  features/form2.feature
  features/lookup.feature
  features/vue.feature
  src/Form.php
  src/jsCallback.php
  template/semantic-ui/form-success.html
  template/semantic-ui/form-success.pug
Labels: in review

#1012 [Feature] Dropdown Cascade Form Field
  demos/cascade-dropdown.php
  docs/field.rst
  src/FormField/DropDownCascade.php
Labels: in review

#1034 [fix] - Allow onDelete or onUpload callback to run within another callback
  demos/upload.php
  src/FormField/Upload.php
Labels: in review

#1018 [refactor] AutoComplete into Lookup
  demos/card-deck.php
  demos/cascade-dropdown.php
  demos/dropdown-plus.php
  demos/form3.php
  demos/grid.php
  demos/grid_action.php
  demos/index.php
  demos/init.php
  demos/jsactionsgrid.php
  demos/lookup.php
  demos/tutorial_actions.php
  docs/field.rst
  features/lookup.feature
  src/FormField/AutoComplete.php
  src/FormField/Lookup.php
  src/FormField/MultiLine.php
  src/FormField/TextArea.php
  src/FormField/TreeItemSelector.php
  src/TableColumn/Delete.php
  src/TableColumn/Generic.php
  src/jsSSE.php
  template/semantic-ui/formfield/autocomplete.html
  template/semantic-ui/formfield/autocomplete.pug
  template/semantic-ui/formfield/lookup.html
  template/semantic-ui/formfield/lookup.pug
  tests/DemoCallExitTest.php
  tests/TagTest.php
Labels: in review

#1035 Update Grid.php
  src/Grid.php
Labels: in review

#939 Delete config.yml
  .github/config.yml
Labels: BLOCKED

#979 fomantic update 2.8.4
  src/App.php
Labels: BLOCKED

#873 Add workflow for deploying "ui.agiletoolkit.org" automatically.
  .codefresh/ui-build-deploy.yaml
  .dockerignore
  .github/workflows/ui-demo.yml
  .gitignore
  Dockerfile
  atk4-ui-helm/.helmignore
  atk4-ui-helm/Chart.yaml
  atk4-ui-helm/templates/NOTES.txt
  atk4-ui-helm/templates/_helpers.tpl
  atk4-ui-helm/templates/deployment.yaml
  atk4-ui-helm/templates/ingress.yaml
  atk4-ui-helm/templates/service.yaml
  atk4-ui-helm/values.yaml
  composer.lock
Labels: in progress

#1048 Fix demo
  composer.json
  demos/table.php
Labels: in review
