Repository atk4/ui, pull requests merged in 2020-09, with the labels that each got.

#1430 [fix] - Js Package bundle
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/components/item-search.component.js
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/services/panel.service.js
  js/webpack.config.js
  src/Component/ItemSearch.php
  tests-behat/basicexecutor.feature
  tests-behat/bootstrap/Context.php
  tests-behat/callback.feature
  tests-behat/card.feature
  tests-behat/crud.feature
  tests-behat/filter.feature
  tests-behat/form.feature
  tests-behat/grid.feature
  tests-behat/js.feature
  tests-behat/lookup.feature
  tests-behat/modal.feature
  tests-behat/rightpanel.feature
  tests-behat/tab.feature
  tests-behat/useraction.feature
  tests-behat/vue.feature
Labels: RTM

#1282 Add type validation to factory calls
  src/App.php
  src/Table.php
Labels: RTM

#1429 Fix code for updated Model class (prevent reload with a different record
  demos/_unit-test/callback.php
  demos/collection/jsactionsgrid.php
  demos/form-control/multiline.php
  demos/layout/layout-panel.php
  src/Lister.php
  src/Table.php
Labels: RTM

#1436 Norm phpunit config and CS config
  .php_cs.dist
  phpunit.xml.dist
  src/App.php
  src/Lister.php
  src/Table.php
  tests/DemosTest.php
Labels: RTM

#1441 Update code for updated "id" handling/checking
  src/Form/Control/Radio.php
  src/View.php
  tests/PostTest.php
Labels: RTM

#1442 Update code for dropped magical "id" property from Model
  demos/collection/table.php
  demos/collection/table2.php
  demos/form-control/dropdown-plus.php
  demos/form-control/input2.php
  demos/init-db.php
  demos/tutorial/intro.php
  docs/form-control.rst
  docs/label.rst
  docs/multiline.rst
  src/Card.php
  src/CardDeck.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Radio.php
  src/Lister.php
  src/Table.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ModalExecutor.php
Labels: RTM

#1446 Fix code to not use dropped legacy/array OR
  src/Form/Control/Lookup.php
  src/Grid.php
Labels: RTM

#1447 Improve doc only
  src/App.php
  tests/DemosTest.php
Labels: RTM

#1445 [fix] - CascadeDropdown rendering
  src/Form/Control/DropdownCascade.php
Labels: RTM

#1435 Refactor Js Atk Bundle eventBus
  demos/javascript/vue-component.php
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-utils.js
  js/src/components/inline-edit.component.js
  js/src/components/item-search.component.js
  js/src/components/multiline/multiline-header.component.js
  js/src/components/multiline/multiline-row.component.js
  js/src/components/multiline/multiline.component.js
  js/src/plugin.js
  js/src/services/vue.service.js
  src/Component/InlineEdit.php
  src/Component/ItemSearch.php
  src/Form/Control/Multiline.php
  src/JsVueService.php
  src/View.php
  template/semantic-ui/inline-edit.html
  template/semantic-ui/inline-edit.pug
  template/semantic-ui/item-search.html
  template/semantic-ui/item-search.pug
Labels: BC-break, RTM

#1449 Feature/fix scopebuilder
  src/Form/Control/ScopeBuilder.php
Labels: RTM, Saasty.io :building_construction:

#1451 Fix Multiline component
  demos/form-control/multiline.php
  src/Form/Control/Multiline.php
Labels: RTM

#1448 [feature] Vue Component loaded dynamically
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-semantic-ui.js
  js/src/atk-utils.js
  js/src/components/query-builder/query-builder.component.vue
  js/src/services/vue.service.js
  js/webpack.config.js
Labels: RTM

#1452 [fix] - Bundle loading path
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/webpack.config.js
  src/App.php
  template/semantic-ui/html.html
  template/semantic-ui/html.pug
Labels: RTM, Saasty.io :building_construction:

#1453 Catch all errors by App handler incl. php notices
  src/App.php
Labels: RTM, enhancement :+1:

#1454 [fix] set defautl path when missing
  js/src/agile-toolkit-ui.js
Labels: RTM, Saasty.io :building_construction:

#1458 [fix] Behat test when using chunk js file
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/components/query-builder/query-builder.component.vue
  js/src/services/vue.service.js
  js/webpack.config.js
  template/semantic-ui/html.html
  template/semantic-ui/html.pug
  tests-behat/bootstrap/Context.php
Labels: RTM
