Repository atk4/ui, pull requests merged in 2020-05, with the labels that each got.

#1151 [fix] - Header Menu Size
  public/agileui.css
  public/agileui.less
Labels: Saasty.io :building_construction:

#1155 [fix] Reload on Callback
  demos/layout/layout-panel.php
  features/rightpanel.feature
  src/Callback.php
  src/Panel/Content.php
  src/jsCallback.php
  src/jsSSE.php
Labels: Saasty.io :building_construction:

#1181 [fix] Radio Input Field
  src/FormField/Radio.php
Labels: Saasty.io :building_construction:

#1137 Fix script/style escaping in App::getTag()
  src/App.php
Labels: help wanted

#1207 Pass value with correct escaping, not embed
  demos/collection/tablefilter.php
Labels: URGENT
