Repository atk4/ui, pull requests merged in 2020-10, with the labels that each got.

#1465 Fix JS bundle URL escape
  demos/javascript/vue-component.php
  src/App.php
  src/JsExpression.php
  template/semantic-ui/html.html
  template/semantic-ui/html.pug
Labels: RTM, bug :beetle:

#1466 Cleanup JsExpression to string/JS
  demos/_includes/FlyersForm.php
  demos/form-control/multiline.php
  demos/form-control/tree-item-selector.php
  demos/form/form-section.php
  demos/form/form3.php
  demos/others/sticky2.php
  docs/table.rst
  docs/tree-item-selector.rst
  src/App.php
  src/Console.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Multiline.php
  src/Form/Control/TreeItemSelector.php
  src/JsCallback.php
  src/JsChain.php
  src/JsConditionalForm.php
  src/JsExpression.php
  src/JsExpressionable.php
  src/JsFunction.php
  src/JsNotify.php
  src/JsReload.php
  src/JsSse.php
  src/JsToast.php
  src/Persistence/Ui.php
  src/Table.php
  src/UserAction/JsEventExecutor.php
  src/View.php
  tests/CallbackTest.php
  tests/DemosTest.php
Labels: BC-break, RTM

#1457 Dropdown refactor
  demos/basic/menu.php
  src/Dropdown.php
  template/semantic-ui/dropdown.html
  template/semantic-ui/dropdown.pug
Labels: BC-break, RTM

#1463 Refactor ScopeBuilder date picker
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-utils.js
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/components/share/atk-date-picker.js
  src/Form/Control/ScopeBuilder.php
Labels: RTM

#1464 Feature/add date picker to Multiline
  demos/form-control/multiline.php
  js/Release.md
  js/src/components/multiline/multiline-cell.component.js
  js/src/components/multiline/multiline-row.component.js
  js/src/components/multiline/multiline.component.js
  src/Form/Control/Multiline.php
Labels: RTM, waitingForAnotherPR

#1470 Bundle repeatable build JS files
  .github/workflows/bundler.yml
  .github/workflows/test-release-drafter.yml
  .github/workflows/test-unit.yml
  .gitignore
  demos/Dockerfile
  js/package-lock.json
  public/.gitignore
  public/atk-vue-inline-edit.min.js
  public/atk-vue-item-search.min.js
  public/atk-vue-multiline.min.js
  public/atk-vue-query-builder.min.js
  public/atk-vue-tree-item-selector.min.js
  public/atkjs-ui.min.js
  public/vendors.min.js
  src/App.php
Labels: RTM, bug :beetle:

#1479 Fix owner prop to getter phpdoc
  src/AbstractView.php
  src/Table/Column.php
Labels: RTM

#1478 Add MSSQL testing
  .github/workflows/test-unit.yml
  phpunit-mssql.xml.dist
Labels: RTM

#1489 Use proper boolean decorator for CardTable
  src/CardTable.php
Labels: CherrypickIntoLowestSupportedBranch, RTM

#1486 [fix] Lookup
  demos/_demo-data/dump.sql
  demos/_unit-test/lookup.php
  demos/form-control/dropdown-plus.php
  demos/form-control/lookup-dep.php
  demos/init-db.php
  demos/special/cascade-dropdown.php
  src/Form/Control/Lookup.php
  tests-behat/lookup.feature
Labels: CherrypickIntoLowestSupportedBranch, RTM

#1493 Test using lowest deps
  .github/workflows/test-unit.yml
  composer.json
Labels: RTM

#1497 Require behat/mink instead of hotfix symfony/css-selector dep
  composer.json
Labels: RTM

#1494 [fix] Behat Lookup test
  demos/_unit-test/lookup.php
  src/App.php
  src/Form/Control/Lookup.php
  tests-behat/bootstrap/Context.php
Labels: CherrypickIntoLowestSupportedBranch, waiting for author

#1500 Trigger Bundler CI using better filter
  .github/workflows/bundler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-release-drafter.yml
  .github/workflows/test-unit.yml
  .github/workflows/zip-file.yml
Labels: RTM

#1501 Patch Behat until behat/mink is released to improve testing speed
  .github/workflows/test-unit.yml
  tests-behat/bootstrap/Context.php
Labels: RTM

#1505 Revert "Trigger Bundler CI using better filter"
  .github/workflows/bundler.yml
Labels: RTM

#1509 Add word "dangerously" to template setters method names and rename some render() and load*() methods
  demos/collection/table2.php
  demos/javascript/vue-component.php
  docs/form-control.rst
  docs/template.rst
  src/App.php
  src/Form.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Input.php
  src/Form/Control/Multiline.php
  src/Form/Control/TreeItemSelector.php
  src/Form/Layout.php
  src/GridLayout.php
  src/HtmlTemplate.php
  src/Layout/Centered.php
  src/Lister.php
  src/Paginator.php
  src/Table.php
  src/Table/Column/Link.php
  src/Table/Column/Multiformat.php
  src/UserAction/ModalExecutor.php
  src/UserAction/PreviewExecutor.php
  src/View.php
  src/VirtualPage.php
  tests/HtmlTemplateTest.php
Labels: BC-break, RTM

#1512 Fix Template::cloneRegion
  src/HtmlTemplate.php
Labels: RTM, bug :beetle:

#1513 Deprecate Template array like access
  .github/workflows/test-unit.yml
  demos/interactive/popup.php
  demos/layout/layouts_admin.php
  docs/form.rst
  docs/template.rst
  docs/view.rst
  src/Form.php
  src/Form/Control/Radio.php
  src/HtmlTemplate.php
  src/Table.php
  src/Table/Column/ColorRating.php
  tests/HtmlTemplateTest.php
Labels: BC-break, RTM

#1517 [fix] View plane demo
  demos/basic/view.php
Labels: RTM

#1485 [fix] ScopeBuilder operator for hasOne
  src/Form/Control/ScopeBuilder.php
Labels: CherrypickIntoLowestSupportedBranch, RTM

#1518 [fix] Multitable demo
  demos/collection/multitable.php
Labels: RTM

#1510 Fix code for removed deprecated string seed support
  demos/collection/multitable.php
  demos/javascript/reloading.php
  demos/others/sticky.php
Labels: RTM

#1508 Rework HtmlTemplate from nested array to tree/OOP structure
  demos/collection/jssortable.php
  demos/layout/templates/layout1.html
  demos/layout/templates/layout1.pug
  docs/template.rst
  src/GridLayout.php
  src/HtmlTemplate.php
  src/HtmlTemplate/TagTree.php
  src/HtmlTemplate/Value.php
  tests-behat/bootstrap/Context.php
  tests/HtmlTemplateTest.php
Labels: BC-break, MAJOR, RTM

#1519 Fix test case class name
  .github/workflows/test-unit.yml
  tests/ForFieldUiTest.php
Labels: RTM

#1522 Move demo data import from SQL to code
  .gitignore
  demos/_demo-data/create-sqlite-db.php
  demos/_demo-data/dump.sql
  demos/init-app.php
  demos/init-autoloader.php
Labels: RTM, waitingForAnotherPR

#1526 Verbose Behat - display stack trace on exception
  .github/workflows/test-unit.yml
Labels: RTM

#1525 Fix jQueryWait typo - do not wait 1 000 000 times longer
  tests-behat/bootstrap/Context.php
Labels: RTM, bug :beetle:

#1499 Fix/enable Lookup Behat test
  demos/_unit-test/lookup.php
  tests-behat/bootstrap/Context.php
  tests-behat/bootstrap/ContextDump.php
  tests-behat/lookup.feature
Labels: RTM
