Repository atk4/ui, pull requests merged in 2020-12, with the labels that each got.

#1552 [fix] Card Deck demo
  demos/collection/card-deck.php
  demos/init-app.php
  demos/interactive/jssortable.php
  src/Card.php
Labels: RTM

#1558 [fix] Lookup add condition after model is set
  src/Form/Control/Lookup.php
Labels: RTM

#1566 [fix] ReadMe link
  README.md
Labels: RTM

#1565 [fix] Property access for Modal Executor
  demos/collection/crud.php
  src/UserAction/ModalExecutor.php
Labels: RTM

#1541 Fix strict types in App::getTag()
  src/Persistence/Ui.php
  src/View.php
  tests/DemosTest.php
Labels: RTM, bug :beetle:, waitingForReaction

#1573 Fix App::encodeJson regex backtrack limit issue
  src/App.php
  tests/JsIntegrationTest.php
  tests/JsTest.php
Labels: bug :beetle:

#1554 Fix all non-undefined PHPStan ignores 1/2
  .codefresh/ui-build-deploy.yml
  demos/_unit-test/scope-builder-to-query.php
  demos/collection/multitable.php
  demos/init-db.php
  phpstan.neon.dist
  src/Accordion.php
  src/Card.php
  src/Console.php
  src/Form/Control/Checkbox.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Multiline.php
  src/Form/Control/Radio.php
  src/Form/Control/Upload.php
  src/Form/Layout/Custom.php
  src/HtmlTemplate.php
  src/Jquery.php
  src/JsCallback.php
  src/Layout/Admin.php
  src/Layout/NavigableInterface.php
  src/Lister.php
  src/Loader.php
  src/Menu.php
  src/Modal.php
  src/Panel/Right.php
  src/Popup.php
  src/Table/Column/FilterModel.php
  src/Table/Column/Link.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ModalExecutor.php
  src/View.php
  tests-behat/bootstrap/Context.php
  tests/DemosTest.php
  tools/get-assets.php
Labels: RTM

#1579 Better hasOne usage
  demos/form-control/dropdown-plus.php
  demos/init-db.php
Labels: RTM

#1581 Improve PHPStan to level 5
  composer.json
  demos/Dockerfile
  demos/form/form.php
  demos/init-db.php
  phpstan.neon.dist
  src/App.php
  src/HtmlTemplate.php
  src/Loader.php
Labels: RTM

#1577 Feature/ Add Lookup to Multiline
  demos/_unit-test/scope-builder.php
  demos/form-control/multiline.php
  demos/special/multiline-containsmany.php
  docs/multiline.rst
  js/Release.md
  js/package.json
  js/src/atk-utils.js
  js/src/components/multiline/multiline-body.component.js
  js/src/components/multiline/multiline-cell.component.js
  js/src/components/multiline/multiline-header.component.js
  js/src/components/multiline/multiline-row.component.js
  js/src/components/multiline/multiline.component.js
  js/src/components/share/atk-lookup.js
  js/src/services/api.service.js
  phpstan.neon.dist
  public/atk-vue-inline-edit.min.js
  public/atk-vue-item-search.min.js
  public/atk-vue-multiline.min.js
  public/atk-vue-query-builder.min.js
  public/atk-vue-tree-item-selector.min.js
  public/atkjs-ui.min.js
  public/vendors.min.js
  src/Callback.php
  src/Form/Control/Multiline.php
  src/Form/Control/ScopeBuilder.php
  src/Form/Control/VueLookupTrait.php
  src/JsCallback.php
  tests-behat/scopebuilder.feature
Labels: BC-break, RTM

#1582 Callback accepts \Closure only
  src/Callback.php
  src/Form/Control/Lookup.php
  src/Form/Control/VueLookupTrait.php
Labels: bug :beetle:
