Repository atk4/ui, pull requests merged in 2020-08, with the labels that each got.

#1390 Move Behat testing to GitHub Actions
  .github/workflows/test-behat.yml
  .github/workflows/test-unit.yml
  .travis.yml
  behat.yml.dist
Labels: RTM

#1377 Callback/sticky args refactor
  demos/_unit-test/callback.php
  demos/_unit-test/callback_2.php
  demos/_unit-test/console.php
  demos/_unit-test/console_exec.php
  demos/_unit-test/console_run.php
  demos/_unit-test/exception.php
  demos/_unit-test/post.php
  demos/_unit-test/reload.php
  demos/_unit-test/sse.php
  demos/form-control/checkbox.php
  demos/form/form5.php
  demos/init-db.php
  demos/interactive/scroll-grid-container.php
  demos/interactive/scroll-grid.php
  demos/interactive/virtual.php
  demos/interactive/wizard.php
  demos/obsolete/notify.php
  demos/obsolete/notify2.php
  demos/tutorial/actions.php
  features/bootstrap/atk4/ui/behat/FeatureContextBasic.php
  features/callback.feature
  features/rightpanel.feature
  features/useraction.feature
  src/App.php
  src/Callback.php
  src/Component/InlineEdit.php
  src/Dropdown.php
  src/Form.php
  src/Form/Control/Multiline.php
  src/Form/Control/Upload.php
  src/JsCallback.php
  src/Loader.php
  src/Modal.php
  src/Panel/Content.php
  src/Popup.php
  src/Table.php
  src/Table/Column/FilterPopup.php
  src/VirtualPage.php
  src/Wizard.php
  tests/CallbackTest.php
  tests/DemosTest.php
  tests/FormTest.php
Labels: BC-break, RTM

#1391 Test using locally built JS/CSS files
  .github/workflows/test-behat.yml
Labels: RTM, Tests, bug :beetle:

#1389 Add Behat testing with Firefox
  .github/workflows/test-behat.yml
  behat.yml.dist
  composer.json
  demos/collection/actions.php
  demos/collection/multitable.php
  demos/init-db.php
  tests-behat/basicexecutor.feature
  tests-behat/bootstrap/Context.php
  tests-behat/bootstrap/ContextDump.php
  tests-behat/callback.feature
  tests-behat/card.feature
  tests-behat/crud.feature
  tests-behat/filter.feature
  tests-behat/form.feature
  tests-behat/grid.feature
  tests-behat/js.feature
  tests-behat/lookup.feature
  tests-behat/modal.feature
  tests-behat/rightpanel.feature
  tests-behat/tab.feature
  tests-behat/useraction.feature
  tests-behat/vue.feature
Labels: RTM, Tests, refactor

#1392 Improve Behat testing and handle all waits using hooks
  .github/workflows/test-behat.yml
  behat.yml.dist
  js/src/components/item-search.component.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/services/panel.service.js
  tests-behat/basicexecutor.feature
  tests-behat/bootstrap/Context.php
  tests-behat/bootstrap/ContextDump.php
  tests-behat/callback.feature
  tests-behat/card.feature
  tests-behat/crud.feature
  tests-behat/filter.feature
  tests-behat/form.feature
  tests-behat/grid.feature
  tests-behat/js.feature
  tests-behat/lookup.feature
  tests-behat/modal.feature
  tests-behat/rightpanel.feature
  tests-behat/tab.feature
  tests-behat/useraction.feature
  tests-behat/vue.feature
Labels: RTM, Tests

#1396 Add AbstractView and use it as a base class for Callback
  docs/render.rst
  src/AbstractView.php
  src/App.php
  src/Callback.php
  src/CallbackLater.php
  src/Console.php
  src/Form/Layout.php
  src/JsCallback.php
  src/Loader.php
  src/Menu.php
  src/Panel/Content.php
  src/Table.php
  src/Table/Column/Delete.php
  src/Table/Column/Multiformat.php
  src/Template.php
  src/View.php
  src/Wizard.php
Labels: BC-break, Consistency, RTM, enhancement :+1:

#1398 [fix] check if any data recalled by FilterModel
  src/Table/Column/FilterModel.php
  src/Table/Column/FilterModel/TypeEnum.php
Labels: bug :beetle:

#1402 [fix] closure variable name
  src/Console.php
Labels: bug :beetle:

#1404 Improve Behat testing - always fail if page contains uncaught exception
  tests-behat/bootstrap/Context.php
Labels: Tests

#1407 View::_getStickyArgs() returns args incl. from self
  src/AbstractView.php
  src/Callback.php
Labels: Cleanup, RTM

#1410 Fix input form attribute as soon as possible, needed for partial render
  src/Form.php
  src/Form/Control.php
Labels: RTM, URGENT, bug :beetle:

#1408 Extract native code instead of string eval in demos
  demos/_includes/Demo.php
  demos/_includes/PromotionText.php
  demos/tutorial/actions.php
  demos/tutorial/intro.php
Labels: RTM, enhancement :+1:

#1412 Render full exception details on ModalExecutor error
  src/UserAction/ModalExecutor.php
Labels: RTM

#1417 Rename Upload control URL args
  js/Release.md
  js/package.json
  js/src/plugins/file-upload.plugin.js
  src/App.php
  src/Form/Control/Upload.php
Labels: BC-break, enhancement :+1:

#1397 No app/global sticky Callback
  demos/interactive/loader.php
  src/AbstractView.php
  src/Callback.php
  src/Loader.php
  src/Modal.php
  src/Panel/Content.php
  src/Panel/Right.php
  src/Popup.php
  src/View.php
  src/VirtualPage.php
  src/Wizard.php
Labels: BC-break, Consistency, MAJOR, enhancement :+1:

#1418 Improve comment CS
  demos/_includes/DemoLookup.php
  demos/collection/grid.php
  demos/collection/tablecolumnmenu.php
  demos/collection/tablefilter.php
  demos/form-control/dropdown-plus.php
  demos/form-control/upload.php
  demos/form/form-section.php
  demos/form/jscondform.php
  demos/interactive/card.php
  demos/interactive/loader.php
  demos/interactive/modal.php
  demos/interactive/scroll-container.php
  demos/interactive/scroll-grid-container.php
  demos/javascript/vue-component.php
  docs/autocomplete.rst
  docs/fileupload.rst
  docs/form-control.rst
  docs/form.rst
  docs/multiline.rst
  js/README.md
  js/src/agile-toolkit-ui.js
  js/src/components/multiline.component.js
  js/src/directives/click-outside.directive.js
  js/src/plugin.js
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/column-resizer.plugin.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/confirm.plugin.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/plugins/js-sortable.plugin.js
  js/src/plugins/scroll.plugin.js
  js/src/services/api.service.js
  js/src/services/form.service.js
  js/src/services/modal.service.js
  js/src/services/panel.service.js
  js/src/services/popup.service.js
  src/Accordion.php
  src/Crud.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Input.php
  src/Form/Control/TreeItemSelector.php
  src/Form/Control/Upload.php
  src/Grid.php
  src/ItemsPerPageSelector.php
  src/Layout/Maestro.php
  src/Modal.php
  src/Popup.php
  src/Table.php
  src/Table/Column.php
  src/Table/Column/FilterModel/TypeEnum.php
  src/Table/Column/FilterPopup.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/ModalExecutor.php
  src/View.php
  template/semantic-ui/table.pug
  tests-behat/bootstrap/Context.php
Labels: Cleanup

#1419 Do not bundle Vue licence file
  js/webpack.config.js
Labels: RTM

#1386 Use native and/or in Vue Scope builder internally
  js/src/components/query-builder/query-builder.component.vue
  src/Form/Control/ScopeBuilder.php
Labels: RTM

#1421 Do not use compact() function
  src/Form/Control/ScopeBuilder.php
  src/Table/Column.php
Labels: Cleanup, RTM

#1425 Add possibility to change Template class in loadTemplate; clean up App
  src/App.php
  tests/AppTest.php
Labels: RTM, enhancement :+1:

#1280 Lint (incl. CS) JS files in GH CI
  .github/workflows/test-behat.yml
  js/.eslintrc.js
  js/.eslintrc.json
  js/Release.md
  js/babel.config.js
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-semantic-ui.js
  js/src/components/inline-edit.component.js
  js/src/components/item-search.component.js
  js/src/components/multiline.component.js
  js/src/components/multiline/multiline-body.component.js
  js/src/components/multiline/multiline-cell.component.js
  js/src/components/multiline/multiline-header.component.js
  js/src/components/multiline/multiline-readonly.component.js
  js/src/components/multiline/multiline-row.component.js
  js/src/components/multiline/multiline-textarea.component.js
  js/src/components/query-builder/fomantic-ui-group.component.vue
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/components/query-builder/query-builder.component.vue
  js/src/components/tree-item-selector/tree-item-selector.component.js
  js/src/directives/click-outside.directive.js
  js/src/directives/commons.directive.js
  js/src/helpers/table-dropdown.helper.js
  js/src/helpers/url.helper.js
  js/src/plugin.js
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/atk.plugin.js
  js/src/plugins/column-resizer.plugin.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/confirm.plugin.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/file-upload.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/plugins/js-sortable.plugin.js
  js/src/plugins/notify.plugin.js
  js/src/plugins/reload-view.plugin.js
  js/src/plugins/scroll.plugin.js
  js/src/plugins/server-event.plugin.js
  js/src/plugins/sidenav.plugin.js
  js/src/plugins/spinner.plugin.js
  js/src/services/accordion.service.js
  js/src/services/api.service.js
  js/src/services/data.service.js
  js/src/services/form.service.js
  js/src/services/modal.service.js
  js/src/services/panel.service.js
  js/src/services/popup.service.js
  js/src/services/upload.service.js
  js/src/services/vue.service.js
  js/webpack.config.js
  template/semantic-ui/layout/maestro-sidenav.html
  template/semantic-ui/layout/maestro-sidenav.pug
Labels: RTM, help wanted

#1426 Enforce industry standard Airbnb JS Coding Standards
  js/.eslintrc.js
  js/babel.config.js
  js/src/components/item-search.component.js
  js/src/components/multiline.component.js
  js/src/components/multiline/multiline-cell.component.js
  js/src/components/multiline/multiline-header.component.js
  js/src/components/query-builder/fomantic-ui-group.component.vue
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/components/tree-item-selector/tree-item-selector.component.js
  js/src/helpers/table-dropdown.helper.js
  js/src/helpers/url.helper.js
  js/src/plugin.js
  js/src/plugins/ajaxec.plugin.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/create-modal.plugin.js
  js/src/plugins/file-upload.plugin.js
  js/src/plugins/js-search.plugin.js
  js/src/plugins/notify.plugin.js
  js/src/plugins/reload-view.plugin.js
  js/src/plugins/scroll.plugin.js
  js/src/plugins/spinner.plugin.js
  js/src/services/api.service.js
  js/src/services/data.service.js
  js/src/services/form.service.js
  js/src/services/modal.service.js
  js/src/services/panel.service.js
  js/src/services/popup.service.js
  js/src/services/upload.service.js
  js/webpack.config.js
  tests-behat/basicexecutor.feature
  tests-behat/callback.feature
  tests-behat/card.feature
  tests-behat/crud.feature
  tests-behat/filter.feature
  tests-behat/form.feature
  tests-behat/grid.feature
  tests-behat/js.feature
  tests-behat/lookup.feature
  tests-behat/modal.feature
  tests-behat/rightpanel.feature
  tests-behat/tab.feature
  tests-behat/useraction.feature
  tests-behat/vue.feature
Labels: help wanted

#1432 [fix] Date picker popup style
  public/agileui.css
  public/agileui.less
Labels: RTM

#1433 [fix] Dropdown using multiple in read only mode
  src/Form/Control/Dropdown.php
Labels: RTM
