Repository atk4/ui, pull requests merged in 2020-07, with the labels that each got.

#1335 Move Layout\Generic to Layout
  demos/layout/layouts_manual.php
  demos/layout/layouts_nolayout.php
  src/App.php
  src/Card.php
  src/Component/InlineEdit.php
  src/Component/ItemSearch.php
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Multiline.php
  src/Form/Control/TreeItemSelector.php
  src/Form/Control/Upload.php
  src/Form/Control/UploadImage.php
  src/Grid.php
  src/Layout.php
  src/Layout/Admin.php
  src/Layout/Centered.php
  src/Layout/Column.php
  src/Layout/Generic.php
  src/Layout/Navigable.php
  src/Layout/NavigableInterface.php
  src/Layout/Product.php
  src/Panel/Right.php
  src/Table/Column.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/FilterModel.php
  src/UserAction/BasicExecutor.php
  src/UserAction/JsEventExecutor.php
  src/UserAction/ModalExecutor.php
  src/jsConditionalForm.php
  src/jsPaginator.php
  src/jsSearch.php
  src/jsSortable.php
Labels: BC-break, refactor

#1338 No echo and output buffering in App::run()
  features/bootstrap/atk4/ui/behat/FeatureContext.php
  features/form.feature
  src/App.php
  src/Console.php
  src/Form.php
  tests/DemosTest.php
Labels: Cleanup

#1348 Fix not freed objects/references
  demos/init-app.php
  demos/interactive/accordion-nested.php
  src/App.php
  tests/CallbackTest.php
  tests/DemosTest.php
Labels: bug :beetle:

#1351 try to fix json encode
  src/App.php
  src/jsExpression.php
  tests/jsTest.php
Labels: RTM

#1337 Move safe "@return bool" phpdoc to code
  src/Accordion.php
  src/App.php
  src/Callback.php
  src/CardDeck.php
  src/CardSection.php
  src/Form/Control/Lookup.php
  src/Form/Layout/Columns.php
  src/Popup.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/FilterModel.php
  src/Table/Column/FilterPopup.php
  src/Template.php
  src/View.php
  src/VirtualPage.php
Labels: RTM

#1353 [fix] Table Action Confirmation Message
  demos/collection/jsactionsgrid.php
  src/Grid.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
Labels: RTM, Saasty.io :building_construction:

#1355 [refactor][fix] MultiLine form control
  src/Form/Control/Multiline.php
Labels: RTM, Saasty.io :building_construction:

#1356 [fix] CRUD afterDelete hook
  src/CRUD.php
Labels: RTM

#1352 [feature] Update to Fomantic-UI version 2.8.6
  demos/form-control/dropdown-plus.php
  demos/form-control/form6.php
  demos/form-control/tree-item-selector.php
  demos/form/form.php
  demos/special/cascade-dropdown.php
  features/form.feature
  src/App.php
Labels: RTM

#1359 [fix] Virtual page rendering
  src/VirtualPage.php
Labels: RTM

#1360 Rename template dirs to match class NS
  src/Form/Control/Checkbox.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Input.php
  src/Form/Control/Lookup.php
  src/Form/Control/Radio.php
  src/Form/Control/Upload.php
  src/Form/Layout.php
  template/semantic-ui/form/control/checkbox.html
  template/semantic-ui/form/control/checkbox.pug
  template/semantic-ui/form/control/dropdown.html
  template/semantic-ui/form/control/dropdown.pug
  template/semantic-ui/form/control/input.html
  template/semantic-ui/form/control/input.pug
  template/semantic-ui/form/control/lookup.html
  template/semantic-ui/form/control/lookup.pug
  template/semantic-ui/form/control/radio.html
  template/semantic-ui/form/control/radio.pug
  template/semantic-ui/form/control/upload.html
  template/semantic-ui/form/control/upload.pug
  template/semantic-ui/form/layout/generic-input.html
  template/semantic-ui/form/layout/generic-input.pug
  template/semantic-ui/form/layout/generic.html
  template/semantic-ui/form/layout/generic.pug
Labels: Cleanup

#1361 Drop App::dbConnect() method
  src/App.php
Labels: BC-break, Cleanup, RTM

#1364 Fix for Model::set() no longer supports array
  demos/collection/table2.php
Labels: RTM

#1275 Close html tag immediatelly - add nested Form support
  js/src/services/form.service.js
  src/Form.php
  src/Table/Column/FilterPopup.php
  src/UserAction/ModalExecutor.php
  src/View.php
  template/semantic-ui/form.html
  template/semantic-ui/form.pug
Labels: BC-break, MAJOR, RTM, URGENT, enhancement :+1:

#1349 Refactor Template and improve performance and type safety
  docs/render.rst
  docs/template.rst
  src/Form/Control/Checkbox.php
  src/Form/Layout.php
  src/GridLayout.php
  src/Header.php
  src/Modal.php
  src/ProgressBar.php
  src/Template.php
  template/semantic-ui/form/control/checkbox.html
  template/semantic-ui/form/control/checkbox.pug
  tests/TemplateTest.php
Labels: BC-break, Cleanup, RTM

#1368 Fix composer develop install issue
  .github/workflows/bundler.yml
  composer.json
Labels: RTM

#1370 Fix form selector for Lookup with dependency support
  src/Form/Control/Lookup.php
Labels: bug :beetle:

#1371 fix composer.json
  composer.json
Labels: RTM

#1381 [fix] Build Query function
  features/crud.feature
  src/App.php
Labels: RTM

#1384 Callable to closure refactor
  docs/accordion.rst
  docs/form-control.rst
  docs/tabs.rst
  src/Accordion.php
  src/App.php
  src/Callback.php
  src/CallbackLater.php
  src/Card.php
  src/CardDeck.php
  src/Component/InlineEdit.php
  src/Console.php
  src/Crud.php
  src/Dropdown.php
  src/Form/Control.php
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Form/Control/Radio.php
  src/Form/Control/TreeItemSelector.php
  src/Form/Control/Upload.php
  src/Form/Layout/Section/Accordion.php
  src/Form/Layout/Section/Tabs.php
  src/Grid.php
  src/ItemsPerPageSelector.php
  src/JsCallback.php
  src/JsNotify.php
  src/JsPaginator.php
  src/JsSortable.php
  src/JsSse.php
  src/JsToast.php
  src/Loader.php
  src/Modal.php
  src/Panel/Content.php
  src/Panel/LoadableContent.php
  src/Panel/Right.php
  src/Popup.php
  src/Table.php
  src/Table/Column.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/DragHandler.php
  src/Table/Column/JsHeader.php
  src/Table/Column/Link.php
  src/Table/Column/Multiformat.php
  src/Table/Column/Status.php
  src/Table/Column/Tooltip.php
  src/Tabs.php
  src/Template.php
  src/UserAction/ArgumentFormExecutor.php
  src/UserAction/BasicExecutor.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/JsEventExecutor.php
  src/UserAction/ModalExecutor.php
  src/View.php
  src/VirtualPage.php
  src/Wizard.php
  tests/FormTest.php
Labels: BC-break, Cleanup

#1127 Introduce FormField\ScopeBuilder
  demos/form-control/query-builder.php
  demos/init-app.php
  demos/tutorial/actions.php
  js/Release.md
  js/package.json
  js/src/components/query-builder/fomantic-ui-group.component.vue
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/components/query-builder/query-builder.component.vue
  js/src/services/vue.service.js
  src/Form/Control/ScopeBuilder.php
Labels: RTM

#1380 Allow upload multiple
  demos/form-control/upload.php
  docs/fileupload.rst
  src/Form/Control/Upload.php
Labels: BC-break, RTM
