Repository atk4/ui, pull requests merged in 2020-06, with the labels that each got.

#1167 Fix wrong URL fallbacks
  src/App.php
Labels: BC-break

#1201 Convert callables to closures and move hook names to constants
  demos/atk-init.php
  demos/collection/actions.php
  demos/collection/crud.php
  demos/collection/grid.php
  demos/collection/jsactions.php
  demos/collection/jssortable.php
  demos/collection/lister-ipp.php
  demos/collection/table.php
  demos/collection/table2.php
  demos/database.php
  demos/interactive/scroll-container.php
  demos/interactive/scroll-lister.php
  demos/javascript/vue-component.php
  docs/label.rst
  docs/lister.rst
  src/ActionExecutor/Basic.php
  src/ActionExecutor/UserAction.php
  src/ActionExecutor/UserConfirmation.php
  src/ActionExecutor/jsArgumentForm.php
  src/ActionExecutor/jsEvent.php
  src/ActionExecutor/jsUserAction.php
  src/App.php
  src/CRUD.php
  src/CallbackLater.php
  src/CardDeck.php
  src/Form.php
  src/FormField/CheckBox.php
  src/FormField/MultiLine.php
  src/FormField/Radio.php
  src/FormLayout/Section/Accordion.php
  src/Grid.php
  src/Lister.php
  src/Table.php
  src/TableColumn/FilterModel/Generic.php
  src/TableColumn/Generic.php
  src/jsSSE.php
Labels: BC-break

#1242 Refactor exception constructor calls to not use array
  demos/database.php
  demos/form/form.php
  demos/form/templates/flyers-form-layout.html
  demos/form/templates/form-custom-layout.html
  docs/form.rst
  src/ActionExecutor/ArgumentForm.php
  src/ActionExecutor/Basic.php
  src/ActionExecutor/UserAction.php
  src/App.php
  src/Button.php
  src/Callback.php
  src/CallbackLater.php
  src/CardTable.php
  src/Console.php
  src/Exception/NoRenderTree.php
  src/Form.php
  src/FormField/CheckBox.php
  src/FormField/Generic.php
  src/FormLayout/Custom.php
  src/FormLayout/_Abstract.php
  src/Grid.php
  src/Lister.php
  src/Persistence/UI.php
  src/Popup.php
  src/Table.php
  src/TableColumn/CheckBox.php
  src/TableColumn/ColorRating.php
  src/TableColumn/Generic.php
  src/TableColumn/Money.php
  src/TableColumn/Multiformat.php
  src/TableColumn/Status.php
  src/TableColumn/Tooltip.php
  src/Template.php
  src/View.php
  src/VirtualPage.php
  src/jsCallback.php
  src/jsExpression.php
  src/jsFunction.php
  src/jsSSE.php
  template/semantic-ui/formfield/lookup.html
  template/semantic-ui/panel/content.pug
  template/semantic-ui/panel/right.pug
Labels: RTM

#1247 Fix exception constructor refactoring
  src/Template.php
Labels: RTM

#1238 Normalize View->add() to always require a seed class like ->factory() already does
  src/View.php
Labels: BC-break, RTM

#1239 Revert fix demo popup - not needed after atk4/core#220
  demos/interactive/popup.php
Labels: RTM

#1240 Upgrade to Fomantic UI 2.8.5
  demos/interactive/tabs.php
  src/App.php
  src/FormLayout/Section/Tabs.php
  src/Tab.php
  src/Tabs.php
  src/jsToast.php
Labels: RTM

#1248 Upgrade JQuery to 3.5.1
  src/App.php
Labels: RTM

#1251 Fix missing DIContainerTrait when StaticAddToTrait is used
  demos/interactive/console.php
  src/Template.php
Labels: RTM

#1234 Delete CHANGELOG.md and build/add it to releases
  CHANGELOG.md
Labels: help wanted

#1249 Prevent minified files normalization in git
  .gitattributes
Labels: RTM

#1261 Few bugfixes
  demos/database.php
  demos/form/form2.php
Labels: RTM

#1246 Render console exceptions using standard HTML exception renderer
  src/App.php
  src/Console.php
Labels: RTM

#1212 Fix current_row type mismatches
  demos/collection/table2.php
  src/Lister.php
  src/Table.php
Labels: RTM, bug :beetle:

#1268 Delete Makefile
  Makefile
  PULL_REQUEST_TEMPLATE.md
Labels: RTM

#1270 Disable action support
  src/Grid.php
  src/TableColumn/Actions.php
Labels: Sponsored :moneybag:

#1245 Fix tests - do not rely on hardcoded/expected names
  .php_cs.dist
  behat-travis.yml
  demos/_unit-test/console.php
  demos/_unit-test/console_exec.php
  demos/_unit-test/console_run.php
  demos/_unit-test/crud.php
  demos/_unit-test/exception.php
  demos/_unit-test/post.php
  demos/_unit-test/reload.php
  demos/_unit-test/sse.php
  demos/atk-init.php
  demos/collection/actions.php
  demos/collection/tablefilter.php
  demos/interactive/card-action.php
  demos/interactive/wizard.php
  demos/obsolete/notify2.php
  features/basicexecutor.feature
  features/bootstrap/atk4/ui/behat/FeatureContext.php
  features/card.feature
  features/crud.feature
  features/filter.feature
  features/grid.feature
  features/js.feature
  features/tab.feature
  src/Console.php
  src/FormField/TreeItemSelector.php
  src/Grid.php
  src/ItemsPerPageSelector.php
  src/Loader.php
  src/Modal.php
  src/Popup.php
  src/VirtualPage.php
  src/Wizard.php
  template/semantic-ui/js-search.html
  template/semantic-ui/js-search.pug
  tests/Concerns/HandlesTable.php
  tests/DemoCallExitTest.php
  tests/GridTest.php
  tests/TableColumnColorRatingTest.php
  tests/TableColumnLinkTest.php
Labels: in progress

#1272 Remove test of disable_functions from Dockerfile
  demos/Dockerfile
Labels: RTM

#1252 Fix usage of hasXXX(), it now return bool only
  src/ActionExecutor/Basic.php
  src/Form.php
  src/FormField/MultiLine.php
  src/FormLayout/_Abstract.php
  src/Grid.php
  src/Persistence/UI.php
  src/Table.php
  src/TableColumn/HTML.php
  src/Template.php
Labels: RTM

#1273 Do not use deprecated properties to check trait presence
  src/TableColumn/FilterModel/Generic.php
  src/View.php
Labels: RTM

#1146 Small normalization changes
  .github/workflows/unit-tests.yml
  .gitignore
  README.md
  codecov.yml
Labels: RTM

#1274 Fix inproper seeds merges
  src/Card.php
  src/CardDeck.php
  src/TableColumn/ActionButtons.php
  src/View.php
  src/jsNotify.php
  tests/jsTest.php
Labels: RTM

#1276 Fix demos autoload if not installed as a main composer project
  demos/atk-init.php
  demos/index.php
  demos/layout/layouts_admin.php
  demos/layout/layouts_manual.php
  demos/layout/layouts_nolayout.php
  src/App.php
  src/Template.php
  tools/get-assets.php
Labels: RTM

#1269 [fix] Admin - Maestro css
  public/agileui.less
  src/Layout/Admin.php
  template/semantic-ui/layout/maestro-sidenav.html
  template/semantic-ui/layout/maestro-sidenav.pug
Labels: RTM

#1205 Simplify use of Persistence\Array_ constructor
  demos/form/form.php
  demos/form/form5.php
  demos/form/html-layout.php
  demos/input/multiline.php
  demos/interactive/modal.php
  demos/interactive/tabs.php
  docs/multiline.rst
  src/TableColumn/FilterModel/Generic.php
  src/TableColumn/FilterModel/TypeBoolean.php
  src/TableColumn/FilterModel/TypeDate.php
  src/TableColumn/FilterModel/TypeDatetime.php
  src/TableColumn/FilterModel/TypeEnum.php
  src/TableColumn/FilterModel/TypeNumber.php
  src/TableColumn/FilterModel/TypeString.php
  src/TableColumn/FilterModel/TypeTime.php
  src/TableColumn/FilterPopup.php
  tests/ForFieldUITest.php
  tests/GridTest.php
  tests/TableColumnColorRatingTest.php
Labels: RTM

#1284 Refactor demo includes
  demos/_includes/DemoActionsUtil.php
  demos/_includes/DemoInvoice.php
  demos/_includes/DemoLookup.php
  demos/_includes/Flyers.php
  demos/_includes/FlyersForm.php
  demos/_includes/Persistence_Faker.php
  demos/_includes/SomeData.php
  demos/_includes/country_actions.php
  demos/atk-init.php
  demos/collection/jsactions2.php
  demos/collection/jsactionsgrid.php
  demos/form/html-layout.php
  demos/input/dropdown-plus.php
  demos/input/field2.php
  demos/input/lookup.php
  demos/interactive/loader.php
  demos/interactive/modal.php
  demos/interactive/virtual.php
  demos/javascript/reloading.php
  demos/layout/layout-panel.php
  demos/layout/layouts_manual.php
  demos/tutorial/actions.php
  demos/tutorial/intro.php
Labels: RTM

#1291 Fix/demo intro
  demos/tutorial/actions.php
  demos/tutorial/intro.php
Labels: RTM, bug :beetle:

#1293 Remove old IE8 CSS compatibility flag
  .github/workflows/bundler.yml
  .github/workflows/test-release-drafter.yml
  .github/workflows/unit-tests.yml
  .travis.yml
Labels: RTM

#1281 Dump Behat page data on/for (the first) failed step
  features/bootstrap/atk4/ui/behat/FeatureContext.php
Labels: RTM

#1301 Cache template files in memory
  src/Template.php
Labels: RTM

#1303 Add phpdoc to anonymous classes in demos
  demos/_unit-test/console_run.php
  demos/basic/button.php
  demos/basic/columns.php
  demos/collection/crud.php
  demos/collection/crud3.php
  demos/collection/multitable.php
  demos/collection/tablecolumns.php
  demos/form/form2.php
  demos/input/multiline.php
  demos/interactive/console.php
  demos/interactive/popup.php
  demos/obsolete/notify2.php
  demos/others/recursive.php
  demos/others/sticky.php
Labels: RTM

#1318 [fix] - Table Generic Hook const
  src/TableColumn/Generic.php
Labels: RTM, Saasty.io :building_construction:

#1315 Use strict array seed
  README.md
  demos/_includes/DemoActionsUtil.php
  demos/collection/crud.php
  demos/collection/grid.php
  demos/collection/jsactions.php
  demos/collection/jsactionsgrid.php
  demos/collection/table2.php
  demos/form/form-section-accordion.php
  demos/form/form-section.php
  demos/form/form3.php
  demos/init-app.php
  demos/init-db.php
  demos/input/multiline.php
  demos/interactive/card-deck.php
  demos/interactive/scroll-grid-container.php
  demos/layout/layouts.php
  demos/layout/layouts_manual.php
  demos/layout/layouts_nolayout.php
  demos/obsolete/crud2.php
  demos/tutorial/actions.php
  docs/app.rst
  docs/core.rst
  docs/filestructure.rst
  docs/form.rst
  docs/multiline.rst
  docs/overview.rst
  docs/quickstart.rst
  docs/render.rst
  docs/seed.rst
  docs/table.rst
  docs/tablecolumn.rst
  docs/view.rst
  src/App.php
  src/CRUD.php
  src/Card.php
  src/CardDeck.php
  src/Form.php
  src/FormLayout/Generic.php
  src/Grid.php
  src/Table.php
  src/TableColumn/ActionButtons.php
  src/TableColumn/ActionMenu.php
  src/TableColumn/Generic.php
  src/View.php
  src/Wizard.php
  tests/CallbackTest.php
  tests/DemosTest.php
  tests/GridTest.php
Labels: RTM

#1320 Hotfix string seeds
  src/ActionExecutor/UserAction.php
  src/Popup.php
Labels: RTM

#1323 fgets can also return false
  src/Console.php
Labels: RTM, Saasty.io :building_construction:

#1324 [fix] Form Conditional Control
  src/Form.php
Labels: RTM

#1325 [fix] Form Section
  src/Form/Layout/Section/Accordion.php
Labels: RTM

#1330 Fix seed usage - icon without class name, instance as class name
  demos/_includes/FlyersForm.php
  demos/collection/crud.php
  demos/collection/grid.php
  demos/collection/table.php
  demos/form-control/input2.php
  demos/form-control/lookup.php
  demos/form-control/tree-item-selector.php
  demos/init-db.php
  demos/interactive/card-deck.php
  demos/interactive/scroll-grid-container.php
  src/Table/Column/ActionButtons.php
  src/Tabs.php
  tests/TableTest.php
Labels: RTM

#1308 [refactor] model user action executors
  demos/_includes/DemoActionsUtil.php
  demos/_unit-test/crud.php
  demos/collection/actions.php
  demos/collection/crud.php
  demos/collection/grid.php
  demos/collection/jsactions.php
  demos/collection/jsactions2.php
  demos/collection/jsactionsgrid.php
  demos/init-db.php
  demos/interactive/card-action.php
  demos/interactive/card-deck.php
  demos/layout/layout-panel.php
  demos/obsolete/crud2.php
  demos/tutorial/actions.php
  docs/crud.rst
  src/ActionExecutor/ArgumentForm.php
  src/ActionExecutor/Basic.php
  src/ActionExecutor/Form.php
  src/ActionExecutor/Interface_.php
  src/ActionExecutor/Preview.php
  src/ActionExecutor/UserAction.php
  src/ActionExecutor/UserConfirmation.php
  src/ActionExecutor/jsArgumentForm.php
  src/ActionExecutor/jsEvent.php
  src/ActionExecutor/jsInterface_.php
  src/ActionExecutor/jsUserAction.php
  src/CRUD.php
  src/Card.php
  src/CardDeck.php
  src/Form.php
  src/Form/Control/Input.php
  src/Grid.php
  src/Menu.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/UserAction/ArgumentFormExecutor.php
  src/UserAction/BasicExecutor.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ExecutorInterface.php
  src/UserAction/FormExecutor.php
  src/UserAction/JsArgumentFormExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/JsEventExecutor.php
  src/UserAction/JsExecutorInterface.php
  src/UserAction/ModalExecutor.php
  src/UserAction/PreviewExecutor.php
  src/View.php
Labels: BC-break, Consistency, refactor, waitingForAnotherPR

#1331 Fix Action button icon
  src/Table/Column/ActionButtons.php
Labels: RTM

#1332 fix property names
  src/UserAction/ArgumentFormExecutor.php
  src/UserAction/ModalExecutor.php
Labels: RTM
