Repository atk4/ui, pull requests merged in 2021-05, with the labels that each got.

#1623 Upgrade atk4/data with strict entity model
  README.md
  composer.json
  demos/_demo-data/create-sqlite-db.php
  demos/_includes/DemoActionsUtil.php
  demos/_unit-test/callback.php
  demos/basic/breadcrumb.php
  demos/collection/crud.php
  demos/collection/lister-ipp.php
  demos/collection/multitable.php
  demos/data-action/actions.php
  demos/data-action/factory-view.php
  demos/data-action/jsactions.php
  demos/data-action/jsactions2.php
  demos/form-control/lookup.php
  demos/form-control/multiline.php
  demos/form/form-section.php
  demos/form/form.php
  demos/form/form2.php
  demos/form/form3.php
  demos/form/form5.php
  demos/form/html-layout.php
  demos/init-db.php
  demos/interactive/card-action.php
  demos/interactive/loader2.php
  demos/javascript/vue-component.php
  demos/layout/layout-panel.php
  demos/layout/layouts_admin.php
  demos/obsolete/notify2.php
  demos/tutorial/actions.php
  demos/tutorial/intro.php
  docs/app.rst
  docs/breadcrumb.rst
  docs/core.rst
  docs/form.rst
  docs/grid.rst
  docs/tablecolumn.rst
  phpstan.neon.dist
  src/App.php
  src/Card.php
  src/CardDeck.php
  src/Crud.php
  src/Form.php
  src/Form/AbstractLayout.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Persistence/Post.php
  src/Table.php
  src/Table/Column/FilterModel.php
  src/Table/Column/FilterPopup.php
  src/UserAction/BasicExecutor.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/FormExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/ModalExecutor.php
  src/View.php
  tests/ForFieldUiTest.php
  tests/FormTest.php
  tests/PostTest.php
Labels: BC-break, Consistency, MAJOR, RTM

#1631 [fix] Multiline
  demos/form-control/multiline.php
  docs/multiline.rst
  docs/type-presentation.rst
  src/Form/Control/Multiline.php
  src/Persistence/Ui.php
  src/Table/Column/Status.php
Labels: BC-break, RTM

#1630 Upgrade phpstan to level 6
  demos/_unit-test/calendar-input.php
  demos/basic/view.php
  demos/collection/multitable.php
  demos/form-control/multiline.php
  demos/form/form.php
  demos/init-app.php
  demos/others/sticky.php
  phpstan.neon.dist
  src/App.php
  src/Card.php
  src/CardDeck.php
  src/Crud.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Form/Control/VueLookupTrait.php
  src/HtmlTemplate.php
  src/ItemsPerPageSelector.php
  src/Jquery.php
  src/JsCallback.php
  src/JsSse.php
  src/Lister.php
  src/Loader.php
  src/Panel/Content.php
  src/Panel/LoadableContent.php
  src/Table.php
  src/Table/Column/KeyValue.php
  src/Table/Column/Labels.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ModalExecutor.php
  src/VirtualPage.php
  src/Wizard.php
  tests-behat/bootstrap/Context.php
  tests/AppTest.php
  tests/ButtonTest.php
  tests/CallbackTest.php
  tests/DemosTest.php
  tests/ExecutorFactoryTest.php
  tests/ForFieldUiTest.php
  tests/FormTest.php
  tests/GridTest.php
  tests/HtmlTemplateTest.php
  tests/JsIntegrationTest.php
  tests/JsTest.php
  tests/ListerTest.php
  tests/LocaleTest.php
  tests/PaginatorTest.php
  tests/PostTest.php
  tests/RenderTreeTest.php
  tests/TableColumnColorRatingTest.php
  tests/TableColumnLinkTest.php
  tests/TableTest.php
  tests/TagTest.php
  tests/ViewTest.php
Labels: RTM

#1632 Drop PHP v7.3 support and upgrade CS Fixer to v3
  .github/workflows/test-unit.yml
  .php-cs-fixer.dist.php
  composer.json
  phpunit-mssql.xml.dist
  phpunit-mysql.xml.dist
  phpunit.xml.dist
  src/AbstractView.php
  src/App.php
  src/HtmlTemplate.php
  src/HtmlTemplate/Value.php
  src/JsExpression.php
  src/Persistence/Ui.php
  src/Template.php
  src/View.php
Labels: BC-break, PHP7.4+, RTM

#1636 [fix] Js Dependencies
  js/package-lock.json
  js/package.json
  js/webpack.config.js
  public/atk-vue-inline-edit.min.js
  public/atk-vue-item-search.min.js
  public/atk-vue-multiline.min.js
  public/atk-vue-query-builder.min.js
  public/atk-vue-tree-item-selector.min.js
  public/atkjs-ui.min.js
  public/vendors.min.js
Labels: RTM

#1637 Bump versions for the next release
  composer.json
  phpstan.neon.dist
  src/Accordion.php
  src/AccordionSection.php
  src/App.php
  src/Behat/Context.php
  src/Crud.php
  src/Form.php
  src/Form/Control/Lookup.php
  src/Form/Layout.php
  src/HtmlTemplate.php
  src/HtmlTemplate/TagTree.php
  src/ItemsPerPageSelector.php
  src/JsVueService.php
  src/Menu.php
  src/Panel/Right.php
  src/Table.php
  src/Table/Column.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/Checkbox.php
  src/Table/Column/ColorRating.php
  src/Table/Column/FilterModel/TypeDatetime.php
  src/Table/Column/FilterPopup.php
  src/Table/Column/Money.php
  src/Template.php
  src/View.php
  tests/HtmlTemplateTest.php
  tools/CoverageUtil.php
  tools/get-assets.php
Labels: RTM
