Repository atk4/ui, pull requests merged in 2021-02, with the labels that each got.

#1600 [fix] - Demo Tutorial
  demos/_includes/DemoInvoice.php
  demos/tutorial/actions.php
Labels: RTM

#1602 [fix] VirtualPage
  demos/_unit-test/lookup-virtual-page.php
  demos/interactive/tabs.php
  demos/interactive/virtual.php
  phpstan.neon.dist
  src/View.php
  src/VirtualPage.php
  tests-behat/lookup.feature
  tests/CallbackTest.php
Labels: BC-break, RTM

#1603 [fix] VirtualPage inside VirtualPage
  demos/_unit-test/virtual-page.php
  demos/interactive/virtual.php
  src/VirtualPage.php
  tests-behat/bootstrap/Context.php
  tests-behat/virtual-page.feature
Labels: RTM

#1604 [fix] - Js search and popupService
  demos/collection/grid.php
  js/.eslintrc.js
  js/Release.md
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/plugins/js-search.plugin.js
  phpstan.neon.dist
  public/atkjs-ui.min.js
  src/Grid.php
  tests-behat/bootstrap/Context.php
  tests-behat/form.feature
  tests-behat/grid.feature
Labels: BC-break, RTM

#1593 Use also different actual name
  composer.json
  demos/_demo-data/create-sqlite-db.php
  demos/init-db.php
Labels: help wanted, waitingForAnotherPR
