Repository atk4/ui, pull requests merged in 2021-11, with the labels that each got.

#1686 Upgrade phpstan to v1.0
  composer.json
  demos/_includes/Counter.php
  phpstan.neon.dist
  src/App.php
  src/Form/AbstractLayout.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Input.php
  src/Form/Control/Lookup.php
  src/Form/Control/ScopeBuilder.php
  src/Form/Control/Upload.php
  src/Grid.php
  src/Lister.php
  src/Persistence/Ui.php
  src/Table/Column/Labels.php
  src/UserAction/ExecutorFactory.php
  src/UserAction/PanelExecutor.php
  src/UserAction/VpExecutor.php
  src/View.php
  tests/CallbackTest.php
  tests/FormTest.php
Labels: RTM

#1690 Fix UI typecast for earlier nullable assertion
  .github/workflows/test-unit.yml
  composer.json
  demos/_demo-data/create-db.php
  src/Console.php
  src/JsExpression.php
  src/Persistence/Ui.php
  tests/FormTest.php
Labels: RTM

#1696 Do not return the same object in View::setModel method
  README.md
  demos/collection/crud.php
  demos/collection/lister-ipp.php
  demos/collection/multitable.php
  demos/data-action/jsactionscrud.php
  demos/form-control/lookup.php
  demos/form-control/multiline-containsmany.php
  demos/interactive/jssortable.php
  demos/interactive/scroll-grid-container.php
  demos/interactive/scroll-grid.php
  demos/interactive/scroll-lister.php
  demos/interactive/scroll-table.php
  demos/javascript/vue-component.php
  demos/tutorial/actions.php
  demos/tutorial/intro.php
  docs/autocomplete.rst
  phpstan.neon.dist
  src/Card.php
  src/CardDeck.php
  src/CardTable.php
  src/Component/InlineEdit.php
  src/Component/ItemSearch.php
  src/Crud.php
  src/Form.php
  src/Form/AbstractLayout.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Form/Control/ScopeBuilder.php
  src/Form/Layout/Columns.php
  src/Grid.php
  src/Table.php
  src/View.php
Labels: BC-break, RTM

#1697 Align with the latest atk4/core
  .github/workflows/test-unit.yml
  composer.json
  demos/_demo-data/create-db.php
  demos/_includes/FakerPersistence.php
  demos/_includes/FlyersForm.php
  demos/_includes/SomeData.php
  demos/collection/crud3.php
  demos/collection/table2.php
  demos/collection/tablecolumns.php
  demos/db.default.php
  demos/form/form.php
  demos/form/form5.php
  demos/form/html-layout.php
  demos/init-app.php
  demos/interactive/modal.php
  demos/interactive/tabs.php
  demos/tutorial/intro.php
  docs/app.rst
  docs/data.rst
  docs/overview.rst
  docs/quickstart.rst
  docs/table.rst
  docs/tabs.rst
  docs/type-presentation.rst
  docs/view.rst
  phpstan.neon.dist
  src/App.php
  src/Form.php
  src/Form/Control/Input.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Form/Layout.php
  src/Persistence/Post.php
  src/Persistence/Ui.php
  src/Table.php
  src/View.php
  tests/DemosTest.php
  tests/ExecutorFactoryTest.php
  tests/GridTest.php
  tests/PostTest.php
  tests/TableColumnColorRatingTest.php
  tests/TableColumnLinkTest.php
  tools/CoverageUtil.php
Labels: RTM

#1702 Handle unhandled Callback exception using custom exception
  demos/init-db.php
  src/App.php
  src/Callback.php
  src/Exception/ExitApplicationError.php
  src/Exception/ExitApplicationException.php
  src/Exception/UnhandledCallbackExceptionError.php
  src/JsChain.php
  src/Table/Column/Checkbox.php
  src/Table/Column/Status.php
  src/View.php
  tests/JsIntegrationTest.php
Labels: RTM

#1709 Add test for unrecoverable App error
  phpstan.neon.dist
  src/App.php
  src/Exception/LateOutputError.php
  tests/AppTest.php
  tests/ExecutorFactoryTest.php
Labels: RTM

#1703 Add filtering possibility for `float` and `atk4_money` DBAL types
  src/Table/Column/FilterModel.php
  src/Table/Column/FilterModel/TypeInteger.php
  src/Table/Column/FilterModel/TypeMoney.php
  src/Table/Column/FilterModel/TypeText.php
Labels: waiting for author

#1712 Fix no longer supported native MSSQL DSN for CI
  .github/workflows/test-unit.yml
Labels: RTM
