Repository atk4/ui, pull requests merged in 2021-09, with the labels that each got.

#1658 Fix Multiline Model validate
  src/Form/Control/Multiline.php
Labels: waitingForAnotherPR, CherrypickIntoLowestSupportedBranch

#1661 Fix Lookup form control
  demos/_includes/DemoLookup.php
  demos/form-control/lookup.php
  src/Form/Control/Lookup.php
  tests-behat/lookup.feature
Labels: RTM

#1662 Refactor callback url test
  demos/interactive/modal.php
  phpstan.neon.dist
  src/Callback.php
  src/VirtualPage.php
  tests/CallbackTest.php
Labels: RTM

#1663 Fix spaces before/after "=>" in comments
  README.md
  demos/form/form2.php
  demos/form/jscondform.php
  demos/interactive/accordion.php
  demos/interactive/sse.php
  demos/interactive/wizard.php
  docs/accordion.rst
  docs/app.rst
  docs/autocomplete.rst
  docs/breadcrumb.rst
  docs/button.rst
  docs/callbacks.rst
  docs/core.rst
  docs/data.rst
  docs/form-control.rst
  docs/form.rst
  docs/grid.rst
  docs/header.rst
  docs/icon.rst
  docs/js.rst
  docs/label.rst
  docs/lister.rst
  docs/menu.rst
  docs/message.rst
  docs/misc.rst
  docs/overview.rst
  docs/popup.rst
  docs/quickstart.rst
  docs/render.rst
  docs/seed.rst
  docs/sticky.rst
  docs/table.rst
  docs/tablecolumn.rst
  docs/tabs.rst
  docs/tree-item-selector.rst
  docs/view.rst
  docs/virtualpage.rst
  docs/wizard.rst
  js/src/plugins/conditional-form.plugin.js
  src/App.php
  src/Form.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Lookup.php
  src/Form/Layout.php
  src/Form/Layout/Custom.php
  src/Header.php
  src/JsChain.php
  src/Lister.php
  src/Modal.php
  src/Table.php
  src/Table/Column/ColorRating.php
  src/Table/Column/KeyValue.php
  src/Table/Column/Status.php
  src/UserAction/JsCallbackExecutor.php
  tests/FormTest.php
Labels: RTM

#1664 Adjust to use DBAL type
  demos/_includes/DemoActionsUtil.php
  demos/_includes/DemoInvoice.php
  demos/_includes/FlyersForm.php
  demos/_includes/Persistence_Faker.php
  demos/_unit-test/calendar-input.php
  demos/_unit-test/scope-builder.php
  demos/form-control/calendar.php
  demos/form-control/input2.php
  demos/form-control/multiline.php
  demos/form-control/tree-item-selector.php
  demos/init-db.php
  demos/tutorial/intro.php
  docs/form-control.rst
  docs/form.rst
  docs/multiline.rst
  docs/tree-item-selector.rst
  src/Behat/Context.php
  src/Callback.php
  src/Component/InlineEdit.php
  src/Form.php
  src/Form/AbstractLayout.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Multiline.php
  src/Persistence/Ui.php
  src/VirtualPage.php
  tests/DemosTest.php
Labels: bug :beetle:, BC-break, RTM
