Repository atk4/ui, pull requests merged in 2021-07, with the labels that each got.

#1647 Update JS and Fomantic UI to 2.8.8
  js/Release.md
  js/package-lock.json
  js/package.json
  public/atk-vue-tree-item-selector.min.js
  public/atkjs-ui.min.js
  public/vendors.min.js
  src/App.php
Labels: RTM

#1524 Fix debouce for Behat testing (fake jQuery.active)
  .github/workflows/build-release.yml
  .github/workflows/test-unit.yml
  js/Release.md
  js/package-lock.json
  js/package.json
  js/src/agile-toolkit-ui.js
  js/src/atk-utils.js
  js/src/helpers/table-dropdown.helper.js
  js/src/plugins/conditional-form.plugin.js
  js/src/plugins/scroll.plugin.js
  phpstan.neon.dist
  public/atkjs-ui.min.js
  src/Behat/Context.php
  src/Component/ItemSearch.php
  src/Form/Control/ScopeBuilder.php
  tests-behat/crud.feature
  tests-behat/grid.feature
  tests-behat/useraction.feature
Labels: Consistency, RTM

#1648 Fix JS lock file and JS CI lint
  js/package-lock.json
  js/package.json
Labels: RTM

#1646 Improve callbacks url generation
  demos/interactive/tabs.php
  demos/interactive/wizard.php
  phpstan.neon.dist
  src/AbstractView.php
  src/App.php
  src/Callback.php
  src/Loader.php
  src/Modal.php
  src/Panel/Content.php
  src/Panel/Right.php
  src/Popup.php
  src/UserAction/ExecutorFactory.php
  src/View.php
  src/VirtualPage.php
  src/Wizard.php
  tests/CallbackTest.php
  tests/DemosTest.php
  tests/FormTest.php
Labels: BC-break, RTM

#1652 Refactor Behat\Context methods
  src/Behat/Context.php
  tests-behat/card.feature
  tests-behat/form.feature
  tests-behat/useraction.feature
Labels: RTM

#1649 Feature/Virtual Page Action Executor
  demos/data-action/action-setup.php
  demos/data-action/jsactions-vp.php
  demos/data-action/jsactions2.php
  demos/init-app.php
  js/Release.md
  js/package.json
  js/src/atk-utils.js
  phpstan.neon.dist
  public/atkjs-ui.min.js
  src/CardDeck.php
  src/JsChain.php
  src/Loader.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ExecutorFactory.php
  src/UserAction/JsExecutorInterface.php
  src/UserAction/ModalExecutor.php
  src/UserAction/StepExecutorTrait.php
  src/UserAction/VpExecutor.php
  src/View.php
  tests-behat/useraction.feature
  tests/DemosTest.php
Labels: RTM

#1575 [fix] Id generation when using Executor as Modal View
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ModalExecutor.php
Labels: RTM
