Repository atk4/ui, pull requests merged in 2021-03, with the labels that each got.

#1595 Prefix/test also all ID fields
  demos/_demo-data/create-sqlite-db.php
  demos/_includes/DemoActionsUtil.php
  demos/collection/lister-ipp.php
  demos/data-action/jsactions2.php
  demos/form/html-layout.php
  demos/init-db.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/ModalExecutor.php
Labels: bug :beetle:

#1610 PHPStan issue 4267 fixed officially
  .github/workflows/test-unit.yml
  composer.json
  phpstan.neon.dist
Labels: RTM

#1550 Feature/Executor refactor
  demos/_includes/DemoActionsUtil.php
  demos/_unit-test/callback_2.php
  demos/_unit-test/crud.php
  demos/_unit-test/lookup.php
  demos/collection/card-deck.php
  demos/collection/crud.php
  demos/collection/grid.php
  demos/data-action/actions.php
  demos/data-action/factory-view.php
  demos/data-action/factory.php
  demos/data-action/jsactions.php
  demos/data-action/jsactionsgrid.php
  demos/init-app.php
  demos/interactive/card-action.php
  demos/layout/layout-panel.php
  demos/tutorial/actions.php
  docs/dataexecutor.rst
  phpstan.neon.dist
  src/App.php
  src/Card.php
  src/CardDeck.php
  src/CardSection.php
  src/Crud.php
  src/Form/Control/Input.php
  src/Grid.php
  src/Menu.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/UserAction/ArgumentFormExecutor.php
  src/UserAction/BasicExecutor.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ExecutorFactory.php
  src/UserAction/ExecutorInterface.php
  src/UserAction/FormExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/JsExecutorInterface.php
  src/UserAction/ModalExecutor.php
  src/UserAction/PreviewExecutor.php
  src/View.php
  tests-behat/callback.feature
  tests-behat/crud.feature
  tests-behat/lookup.feature
  tests/ExecutorFactoryTest.php
Labels: BC-break, RTM
