Repository atk4/ui, pull requests merged in 2022-08, with the labels that each got.

#1810 Unify Control readOnly property case to camelCase
  demos/_includes/DemoLookup.php
  demos/form-control/input2.php
  demos/form-control/multiline.php
  docs/form-control.rst
  src/Form.php
  src/Form/AbstractLayout.php
  src/Form/Control.php
  src/Form/Control/Calendar.php
  src/Form/Control/Checkbox.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Input.php
  src/Form/Control/Lookup.php
  src/Form/Control/Radio.php
  src/Form/Control/Textarea.php
  src/Form/Control/Upload.php
  tests/ForFieldUiTest.php
  tests/HtmlTemplateTest.php
  tests/SessionTraitTest.php
Labels: BC-break

#1816 Fix '0' instead of '' default value for Lookup
  demos/_includes/Demo.php
  demos/_includes/SomeData.php
  demos/basic/columns.php
  demos/form/form2.php
  demos/init-db.php
  docs/form-control.rst
  docs/form.rst
  docs/multiline.rst
  src/CardDeck.php
  src/CardSection.php
  src/Component/InlineEdit.php
  src/Form.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Lookup.php
  src/Grid.php
  src/HelloWorld.php
  src/JsSortable.php
  src/LoremIpsum.php
  src/Modal.php
  src/Panel/Content.php
  src/Panel/Right.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/Checkbox.php
  src/Table/Column/FilterModel.php
  src/Table/Column/KeyValue.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/ExecutorFactory.php
  src/UserAction/ModalExecutor.php
  src/UserAction/PanelExecutor.php
  src/UserAction/VpExecutor.php
  src/View.php
Labels: bug :beetle:

#1828 Fix clickable data UserAction
  phpstan.neon.dist
  src/CardDeck.php
  src/Form/Control.php
  src/Form/Control/Upload.php
  src/JsCallback.php
  src/JsSse.php
  src/Layout/NavigableInterface.php
  src/Menu.php
  src/UserAction/ModalExecutor.php
  src/View.php
Labels: bug :beetle:

#1842 "icon" FUI CSS class is implied by icon component
  demos/form-control/dropdown-plus.php
  demos/form-control/input2.php
  docs/form-control.rst
  docs/icon.rst
  js/src/components/query-builder/fomantic-ui-group.component.vue
  js/src/components/query-builder/fomantic-ui-rule.component.vue
  js/src/components/query-builder/query-builder.component.vue
  js/src/components/tree-item-selector/tree-item-selector.component.js
  js/src/plugins/sidenav.plugin.js
  public/atk-vue-query-builder.min.js
  public/atk-vue-tree-item-selector.min.js
  public/atkjs-ui.min.js
  src/Form/Control/Dropdown.php
  src/Modal.php
  src/Panel/Right.php
  src/Table/Column/ActionMenu.php
  template/form/control/dropdown.html
  template/form/control/dropdown.pug
  template/modal.html
  template/modal.pug
  template/panel/right.html
  template/panel/right.pug
Labels: RTM

#1845 Fix CardDeck action /w entity
  demos/init-db.php
  src/CardDeck.php
Labels: bug :beetle:
