Repository atk4/ui, pull requests merged in 2023-06, with the labels that each got.

#2064 Rename Form\Control\Dropdown::isMultiple property
  demos/form-control/dropdown-plus.php
  demos/form-control/lookup-dep.php
  docs/form-control.rst
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Radio.php
Labels: BC-break

#2067 Add fractional seconds support for time/datetime form control
  demos/_unit-test/calendar-input.php
  demos/_unit-test/scope-builder.php
  demos/basic/view.php
  demos/data-action/jsactions2.php
  demos/form-control/calendar.php
  demos/form-control/dropdown-plus.php
  demos/form-control/lookup.php
  demos/form-control/tree-item-selector.php
  demos/form/form.php
  demos/tutorial/intro.php
  js/src/vue-components/query-builder/fomantic-ui-rule.component.vue
  js/src/vue-components/share/atk-date-picker.js
  public/external/flatpickr/dist/flatpickr.js
  public/external/flatpickr/dist/flatpickr.min.js
  public/external/package-lock.json
  public/external/package.json
  public/js/atk-vue-multiline.js
  public/js/atk-vue-multiline.js.map
  public/js/atk-vue-multiline.min.js
  public/js/atk-vue-multiline.min.js.map
  public/js/atk-vue-query-builder.js
  public/js/atk-vue-query-builder.js.map
  public/js/atk-vue-query-builder.min.js
  public/js/atk-vue-query-builder.min.js.map
  public/js/atkjs-ui.min.js
  src/Behat/Context.php
  src/Form.php
  src/Form/Control.php
  src/Form/Control/Calendar.php
  src/Form/Control/Multiline.php
  src/Form/Control/ScopeBuilder.php
  src/Persistence/Ui.php
  tests-behat/calendar.feature
  tests-behat/scopebuilder.feature
  tests/PersistenceUiTest.php
Labels: MAJOR

#2075 View::set() can be used to set content property only
  demos/form-control/upload.php
  demos/layout/layouts.php
  docs/template.rst
  phpstan.neon.dist
  src/Form.php
  src/HelloWorld.php
  src/ItemsPerPageSelector.php
  src/Menu.php
  src/View.php
  tests/ViewTest.php
Labels: BC-break

#2017 Fix Grid IPP selector
  .php-cs-fixer.dist.php
  demos/collection/grid.php
  src/Behat/Context.php
  src/Grid.php
  src/ItemsPerPageSelector.php
  tests-behat/grid.feature
Labels: bug :beetle:
