Repository atk4/ui, pull requests merged in 2024-01, with the labels that each got.

#2142 Always reload full executor container
  demos/_unit-test/callback-nested.php
  demos/interactive/loader.php
  demos/layout/layout-panel.php
  docs/app.md
  docs/button.md
  docs/table.md
  js/src/plugins/reload-view.plugin.js
  js/src/services/api.service.js
  js/src/services/modal.service.js
  js/src/services/panel.service.js
  js/src/setup-utils.js
  phpstan.neon.dist
  public/css/agileui.less
  public/css/agileui.min.css
  public/css/agileui.min.css.map
  public/js/atkjs-ui.js
  public/js/atkjs-ui.js.map
  public/js/atkjs-ui.min.js
  public/js/atkjs-ui.min.js.map
  src/HtmlTemplate.php
  src/Loader.php
  src/Panel/Right.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/InnerLoaderTrait.php
  src/UserAction/ModalExecutor.php
  src/UserAction/PanelExecutor.php
  src/UserAction/StepExecutorTrait.php
  src/UserAction/VpExecutor.php
  src/Wizard.php
  tests-behat/rightpanel.feature
Labels: MAJOR

#2145 Explicit seed/class suffix in property names
  demos/form/html-layout.php
  phpstan.neon.dist
  src/Card.php
  src/CardDeck.php
  src/Form/Layout.php
  src/Form/Layout/Section.php
  src/Form/Layout/Section/Accordion.php
  src/Form/Layout/Section/Columns.php
  src/Form/Layout/Section/Tabs.php
Labels: BC-break

#2146 Invoke Table::getDataRowHtml() per each row
  src/Lister.php
  src/Table.php
  src/Table/Column/FilterModel.php
  src/Table/Column/FilterModel/TypeBoolean.php
  src/Table/Column/FilterModel/TypeDate.php
  src/Table/Column/FilterModel/TypeDatetime.php
  src/Table/Column/FilterModel/TypeEnum.php
  src/Table/Column/FilterModel/TypeNumber.php
  src/Table/Column/FilterModel/TypeString.php
  src/Table/Column/FilterModel/TypeTime.php
  src/Table/Column/FilterPopup.php
Labels: BC-break

#2147 Do not replace Lister::$model property during render
  demos/collection/table2.php
  src/Form/Control/Radio.php
  src/Lister.php
  src/Table.php
Labels: BC-break

#1868 Allow Grid::addModalAction() button to be disabled
  phpstan.neon.dist
  src/Grid.php
  src/Table/Column/ActionButtons.php
Labels: enhancement :+1:

#2150 Prevent JsCallback chain to be evaluated twice
  demos/data-action/factory-view.php
  docs/callbacks.md
  js/src/setup-fomantic-ui.js
  public/js/atkjs-ui.js
  public/js/atkjs-ui.js.map
  public/js/atkjs-ui.min.js.map
  src/App.php
  src/Card.php
  src/Form.php
  src/JsCallback.php
  src/JsSse.php
  src/UserAction/JsCallbackExecutor.php
  src/View.php
  tests-behat/crud.feature
  tests/FormTest.php
Labels: bug :beetle:
