Repository atk4/ui, pull requests merged in 2024-02, with the labels that each got.

#2152 View::getJs() method returns JsBlock
  docs/view.md
  js/README.md
  js/package.json
  js/src/services/api.service.js
  public/js/atkjs-ui.js
  public/js/atkjs-ui.js.map
  public/js/atkjs-ui.min.js
  public/js/atkjs-ui.min.js.map
  src/App.php
  src/Js/JsFunction.php
  src/Lister.php
  src/View.php
  src/VirtualPage.php
  tests/JsIntegrationTest.php
  tests/JsTest.php
Labels: BC-break

#2092 Fix Lookup initial change detection
  src/Form/Control/Lookup.php
Labels: bug :beetle:

#2155 Unify Table\Column::getTag() params order
  docs/table.md
  src/Table.php
  src/Table/Column.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/ActionMenu.php
  src/Table/Column/ColorRating.php
  src/Table/Column/Money.php
Labels: BC-break

#2159 Remove SessionTrait from Wizard
  demos/interactive/wizard.php
  src/Wizard.php
Labels: BC-break

#2168 Typecast ID for UI strictly using UI persistence
  demos/_unit-test/modal-error.php
  demos/basic/breadcrumb.php
  demos/collection/multitable.php
  demos/form-control/dropdown-plus.php
  demos/form-control/lookup.php
  demos/form-control/multiline.php
  demos/form/form2.php
  demos/init-db.php
  demos/layout/layout-panel.php
  demos/layout/layouts.php
  docs/form-control.md
  src/Card.php
  src/Crud.php
  src/Form.php
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Grid.php
  src/JsCallback.php
  src/Lister.php
  src/Persistence/Ui.php
  src/Table.php
  src/Table/Column/Link.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/StepExecutorTrait.php
  src/View.php
  tests-behat/dropdown.feature
  tests-behat/multiline.feature
Labels: BC-break

#1991 Impl. typecasting for non-display data
  demos/_unit-test/modal-error.php
  demos/basic/breadcrumb.php
  demos/collection/multitable.php
  demos/form-control/calendar.php
  demos/form-control/form6.php
  demos/init-app.php
  demos/interactive/loader2.php
  demos/layout/layout-panel.php
  src/Card.php
  src/Crud.php
  src/Form.php
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Lookup.php
  src/Form/Control/Multiline.php
  src/Form/Control/Radio.php
  src/Grid.php
  src/JsSortable.php
  src/Lister.php
  src/Persistence/Ui.php
  src/Table.php
  src/Table/Column.php
  src/Table/Column/ActionButtons.php
  src/Table/Column/FilterModel/TypeDate.php
  src/Table/Column/FilterModel/TypeDatetime.php
  src/Table/Column/FilterModel/TypeTime.php
  src/Table/Column/Link.php
  src/UserAction/CommonExecutorTrait.php
  src/UserAction/ConfirmationExecutor.php
  src/UserAction/JsCallbackExecutor.php
  src/UserAction/StepExecutorTrait.php
  src/View.php
  tests-behat/loader.feature
  tests-behat/radio.feature
  tests-behat/scroll.feature
  tests/PersistenceUiTest.php
Labels: MAJOR

#2171 Remove model support from HtmlTemplate
  docs/template.md
  src/App.php
  src/Form/Control/Lookup.php
  src/Form/Control/ScopeBuilder.php
  src/HtmlTemplate.php
  src/Lister.php
  src/Table.php
  src/Table/Column/Link.php
  src/Table/Column/Multiformat.php
  src/View.php
  tests/HtmlTemplateTest.php
Labels: BC-break
