Repository atk4/ui, pull requests merged in 2025-01, with the labels that each got.

#2238 Use `int` type for View::setSource() when the data is list
  demos/basic/menu.php
  src/View.php
Labels: BC-break

#2240 Remove bool defaults support from Form\Control::onChange()
  src/Form.php
  src/Form/Control.php
  src/Form/Control/Dropdown.php
  src/Form/Control/Lookup.php
  src/Form/Control/Radio.php
Labels: BC-break

#2209 Impl. clearable dropdown
  demos/_unit-test/grid-rowclick.php
  demos/form-control/dropdown-plus.php
  src/Behat/Context.php
  src/Form/Control/Dropdown.php
  src/Form/Control/DropdownCascade.php
  src/Form/Control/Lookup.php
  src/Form/Control/ScopeBuilder.php
  tests-behat/accordion.feature
  tests-behat/basicexecutor.feature
  tests-behat/callback.feature
  tests-behat/card-deck.feature
  tests-behat/card.feature
  tests-behat/crud.feature
  tests-behat/dropdown.feature
  tests-behat/filter.feature
  tests-behat/form.feature
  tests-behat/grid.feature
  tests-behat/js.feature
  tests-behat/late-error.feature
  tests-behat/lookup.feature
  tests-behat/modal-error.feature
  tests-behat/multiline.feature
  tests-behat/radio.feature
  tests-behat/rightpanel.feature
  tests-behat/scopebuilder.feature
  tests-behat/tab.feature
  tests-behat/tree-item-selector.feature
  tests-behat/useraction.feature
  tests-behat/virtual-page.feature
  tests-behat/vue.feature
Labels: MAJOR

#2076 Fix table column tooltip typecast
  src/Table/Column/Tooltip.php
  tests/Table/Column/LinkTest.php
Labels: bug :beetle:

#2245 Remove JsSse::$closeBeforeUnload property
  js/src/JqueryPlugin/FileUploadPlugin.js
  js/src/JqueryPlugin/ServerEventPlugin.js
  js/src/Service/apiService.js
  public/js/atkjs-ui.js
  public/js/atkjs-ui.js.map
  public/js/atkjs-ui.min.js
  public/js/atkjs-ui.min.js.map
  src/JsSse.php
Labels: BC-break
